### ISSUE TITLE
error while kniting

### ISSUE THREAD

**Issue by raomohsinkhan** [rstudio/bookdown#1022]
Could not find bibliography file: packages.bib
Error running filter C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe:
Filter returned error status 1
Error: pandoc document conversion failed with error 83
Execution halted

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi @raomohsinkhan , 

we are missing some informations here. 

This error just mean that a `packages.bib` file is looked for to render the document with a bibliography because it must have been asked in `bibliography: packages.bib` field in your index.Rmd YAML header. 

I don't think there is an issue with **bookdown** itself here. it may be something with your specific project that you did not share. 

For questions, don't forget there are some great QA place like https://community.rstudio.com

**Comment by mccarthy-m-g** [comment]
This might be a pandoc error caused by the newest update. I reran a previous GitHub Actions build of a bookdown book today (by updating the README.md for the repo), and it went from [working](https://github.com/mccarthy-m-g/bookdown-thesis-template/runs/1324459972?check_suite_focus=true) to [throwing the same error](https://github.com/mccarthy-m-g/bookdown-thesis-template/runs/1489265002?check_suite_focus=true) @raomohsinkhan noted above. It looks like the next version of bookdown might fix the error though, looking at the changes in NEWS.

**Comment by cderv** [comment]
Thanks for sharing @mccarthy-m-g 

I don't think this is the same issue though because from the error message posted above, it seems clear that `packages.bib` was not found
> Could not find bibliography file: packages.bib

In your case, and others you pointed out, the error is preceded by a deprecation warning and is an API mismatch due to Pandoc's update - from 2.11, Pandoc now use `--citeproc` instead of `--filter pandoc-citeproc`, the external file no more being built and shipped with pandoc.

You mainly got the error in your workflow because Pandoc was updated
* Here 2.11.1 where it is not working: https://github.com/mccarthy-m-g/bookdown-thesis-template/runs/1489265002?check_suite_focus=true#step:4:11
* Here 2.10.1 where it is working: https://github.com/mccarthy-m-g/bookdown-thesis-template/runs/1324459972?check_suite_focus=true#step:4:11

Pandoc 2.11+ is supported correctly since **rmarkdown** 2.5. Next bookdown version (so current dev version) will fix a related issue with references being incorrectly placed. 

In order to prevent those type of issue in your CI, you should pin the pandoc version. 
That is why the `pandoc_version` parameter is for in [r-lib/actions/setup-pandoc](https://github.com/r-lib/actions/tree/master/setup-pandoc#usage) for example.

**Comment by cderv** [comment]
@raomohsinkhan have you any update on this ? If no more information from your side, I'll consider this ok as I don't think there is an issue with **bookdown** here. 

Thanks;
