### ISSUE TITLE
bs4_book: add a default 404 page?

### ISSUE THREAD

**Issue by maelle** [rstudio/bookdown#1025]
If there's no 404.html file after building the book, would it make sense to add one that has the book TOC and some standard message?

@hadley 

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by hadley** [comment]
Doesn't that imply a certain deployment workflow? Or do both netlify and github pages use `404.html`?

**Comment by maelle** [comment]
right. :thinking: It seems it'd help in both cases?

* Netlify https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
* GitHub pages https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by hadley** [comment]
And it should be easier than pkgdown because books don't usually have directories (https://github.com/r-lib/pkgdown/issues/1356).

**Comment by maelle** [comment]
Another solution to adding a 404 page would be to have a 404 chapter. However there'd be a need for some tweaks in `build_toc()` in particular to not list the chapter in the TOC. Maybe using the same Pandoc class as what's recommended in https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html (`build_toc()` ignores it for now)

**Comment by maelle** [comment]
Actually it'd be a bad idea to use a 404 chapter when the book is also knit to other formats.

**Comment by cderv** [comment]
Having its own chapter would be the best way to tweak the 404 page. 

> Actually it'd be a bad idea to use a 404 chapter when the book is also knit to other formats.

This would be like with reference pages (see [bookdown-demo](https://github.com/rstudio/bookdown-demo/blob/master/06-references.Rmd)), one would need to use conditional content 

````markdown
`r if (knitr:::is_html_output()) '
# 404 {.unlisted .unnumbered}

It seems you are lost
'`
````

or 

````markdown
```{asis, echo = knitr:::is_html_output()}
# 404 {.unlisted .unnumbered}

It seems you are lost
```
````

> Maybe using the same Pandoc class as what's recommended

However, currently, `.unlisted .unnumbered` is not really supported in **bookdown** in both format. 

And main limitation is that the html files names are based on the id of the section div for the chapter and Pandoc does not support numeric id only (HTML4 does not support it anyway, but HTML5 can I think so Pandoc could support this for HTML5 output). Anyway, we can't have a `404.Rmd` that would contain a `# 404` chapter because, it would not lead to a 404 html file. 

Generating automatically this page would be the only way to go for now if we want this feature. 

Unless we do a special handling in `split_chapter` is we see `<h1>` containing `404`, and we adapt the toc build to be the same feature as Pandoc's TOC supporting the same classes.
