### ISSUE TITLE
nested example blocks are rendered as \BeginKnitrBlock{example} ... \EndKnitrBlock{example} instead of showing as is

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#1038]
I'm having issue with the following Rmd-bookdown document:

    --- 
    title: "Example numbering problem"
    
    site: bookdown::bookdown_site
    documentclass: book
    
    output:
      bookdown::html_document2: default
    
    ---
    
    
    See example code below:
    
        ```{example, c-code}
        Simple C program
        ```
        ```c
        int main() {
        return 0;
        }
        ```
    
    
    See example code below +2 tabs:
    
          ```{example, c2-code}
          Simple C program
          ```
          ```c
          int main() {
          return 0;
          }
          ```
    
    See example code below +4 tabs:
    
            ```{example, c3-code}
            Simple C program
            ```
            ```c
            int main() {
            return 0;
            }
            ```
    
    
    See example code below +4 tabs:
    
    ````
    ```{example, c4-code}
    Simple C program
    ```
    ```c
    int main() {
    return 0;
    }
    ```
    ````
    
    
    Author uses the following syntax
    
        ```{example, c-code5}
        Simple C program
        ```
        ```c
        int main() {
          return 0;
        }
        ```

After knitting to any format it shows 

```
\BeginKnitrBlock{example}<div class="example"><span class="example" id="exm:c-code"><strong>(\#exm:label) </strong></span>Example caption</div>\EndKnitrBlock{example}
```

instead of 

    ```{example, label}
    Example caption
    ```

I think it is a bug. Tried with latest bookdown and preview version of RStudio. Initially was happened with stable RStudio 1.3.1093.

Session info:

```
> xfun::session_info('bookdown')
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS, RStudio 1.4.1071

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=ru_RU.UTF-8   
  LC_MESSAGES=en_US.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3    bookdown_0.21.0005 digest_0.6.27      evaluate_0.14      glue_1.4.2         graphics_3.4.4     grDevices_3.4.4   
  highr_0.8          htmltools_0.5.0    jsonlite_1.7.1     knitr_1.30         magrittr_2.0.1     markdown_1.1       methods_3.4.4     
  mime_0.9           rlang_0.4.9        rmarkdown_2.5.3    stats_3.4.4        stringi_1.5.3      stringr_1.4.0      tinytex_0.27      
  tools_3.4.4        utils_3.4.4        xfun_0.19          yaml_2.2.1        
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

Thanks for the feedback. 

Just to clarify : Is this something that you used and was working before or is it something that you expect to be working ? By something, I understand using indented code blocks and having them preserved in the output, is that right ? 

I ask because I really don't think this has worked before, and the result you get is I think the expected one.

I believe **knitr** will always parse code chunks of this form, no matter the indentation
````
```{engine, options}
...
```
````
It will evaluate them using the selected engine according to the options passed. The different indentations or multiple backticks are tricks that are understood by markdown renderer but not by **knitr** when converting to .Rmd in .md

This is why you get the `\BeginKnitrBlock{example}` part - the `example` engine is known by **bookdown** and so it will be used to format the content of the chunk. 

If you want to include verbatim code chunk, you need to follow this : 
https://bookdown.org/yihui/rmarkdown-cookbook/verbatim-code-chunks.html
That is what is used throughout every books related to R Markdown to show code chunks example. 

With your example, it would be 
`````md
--- 
title: "Example numbering problem"
output:
  bookdown::html_document2: default
---

````
```{example, c4-code}`r ''`
Simple C program
```
```c
int main() {
return 0;
}
```
````

`````
![image](https://user-images.githubusercontent.com/6791940/100990225-f2610600-3551-11eb-90fe-228685680233.png)


Is this what you are looking for ? 
If not, then I misunderstood, so would you please be more precise on the output you would expect so that I better understand ? Thank you!

**Comment by N0rbert** [comment]
I mean that I need to have the above code shown as is

<pre>
```{example, c-code}
Simple C program
```
```c
int main() {
return 0;
}
```
</pre>

without serious changes in the syntax. It is indented, so I believe it should not be parsed at all.
I need syntax without changes, because I want to inform reader about the syntax of labeling Example block for [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems).

I do not exactly remember was it working before or not. ReText shows this code as-is for all above variants.

**Comment by cderv** [comment]
If you want this code shown as is, then what I mentioned above it the way to go. It is the part about Verbatim Code Chunks I linked in my previous post. 

Did you try it ? What is not working as you expect with this documented solution ?

**Comment by N0rbert** [comment]
Thanks, @cderv ! Your method works great. I'll take a note somewhere to remember it.
