### ISSUE TITLE
tidy=TRUE option not working in before_chapter_script when new_session=TRUE (knit and merge method)

### ISSUE THREAD

**Issue by turtlegraphics** [rstudio/bookdown#1049]
I'd like to automatically tidy all R code in the book I'm working on.  The book already has a before_chapter_script, so I want to add this line to it:

`knitr::opts_chunk$set(tidy=TRUE)`

It seems to not be having an effect.

 I do see tidying working when I add `tidy=TRUE` to a chunk as an option.  It also works if I include the line above as the first chunk in the file. 

 I also tried changing `tidy=TRUE` to `echo=FALSE` in the before_chapter_script to see if it would do anything, and it does turn off all echoing.

I can't imagine why this particular setting won't work while others do, so I'm posting here.

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

What tells you it is not working ? It works as expected when I tried.

You did not provide a reproducible example so I needed to build one. 

I tried with bookdown-demo (https://github.com/rstudio/bookdown-demo) : 

1. Clone the project
2. Create a script `_common.R` with this content `knitr::opts_chunk$set(tidy=TRUE)`
3. Add `before_chapter_script: _common.R` in `bookdown.yml`
4. Add this chunk in any doc, for example `02.literature.Rmd`
   ````r 
   ```{r}
   mean(
     1    +   2 
   )
   ```
   ````
5. Build the book

You will have a chunk correctly formated by `formatR`, resulting of `tidy = TRUE` in the resulting HTML
````r
mean(1 + 2)
````

Remove the `before_chapter_script` in bookdown.yml and you'll have a chunk with the formatting unchange
```r
mean(
  1    +   2 
)
```

So this is working fine. 

I'll close this issue for now. If you've still have an issue, please reopen and follow the issue guide: Having a reproducible example will insure we can understand the problem better.

**Comment by cderv** [comment]
Just a confirmation. 

Do you have in your `bookdown.yml` ? 
```yaml
new_session: true
```

**Comment by cderv** [comment]
I can confirm there is a bug with Knit and Merge approach (`new_session: true`) since the change in 581bb639b273a5872e01c10d382065a80a641bf0

We execute the `before_chapter_script` before calling `rmarkdown::render`. So it correctly sets the option `tidy = TRUE` but `rmarkdown::render` will set this option to FALSE by default (https://github.com/rstudio/rmarkdown/blob/5c0aeb078cebb077967e5ee18bfebb937e942d4e/R/render.R#L607)

It is why it works with `echo` and not with `tidy` as this former is not modified by `render()`. 

Before the change in 581bb639b273a5872e01c10d382065a80a641bf0, the `before_chapter_script` was inserted inside the Rmd document, so it would correctly override any default sets by `rmarkdown::render()`. But we made the change because it would mess with line numbering when errors with **knitr**

This `before_chapter_script` and `after_chapter_script` are always tricky. 

You will encounter this issue only with Knit and Merge approach. With `new_session: false`, which is the default, it will work. 

One way to insert common elements in books chapter is to source the script for a chunk in your document directly, or use a child Rmd file. 

Several ways among them these 2

* Use a child document (e.g. `_common.Rmd`) with this content
  ````
  ```{r, include = FALSE, echo = FALSE}
  knitr::opts_chunk$set(tidy = TRUE)
  ```
  ````
  and add 
  ````
  ```{r child = "_common.Rmd"}
  ```
  ````

* Source a script in a chunk 
  ````r
  ```{r include = FALSE}
  source("_common.R")
  ```
  ````

We'll think if this is something we can fix. This issue will only be encountered with option that `rmarkdown::render` set as default and I think it is mainly `tidy = FALSE` and `error = FALSE` that a user would try to change. The others are more oriented toward internal use.


@yihui did you have this side effect in mind when inserting the change in 581bb639b273a5872e01c10d382065a80a641bf0 ? Is there any workaround we could find to also avoid this while keeping 581bb639b273a5872e01c10d382065a80a641bf0 ? 

Otherwise, maybe we should advice to use child Rmd or sourcing R script in each docs as it is efficient and with less side effect as it is user controlled and not a feature we try to maintain. 😅

**Comment by yihui** [comment]
Sorry I didn't foresee this problem. Another workaround is to use `options(knitr.chunk.tidy = TRUE)` in the `before_chapter_script`. This is an undocumented way to set global chunk options, although it has existed for several years.

> Otherwise, maybe we should advice to use child Rmd or sourcing R script in each docs as it is efficient and with less side effect as it is user controlled and not a feature we try to maintain.

This seems to be a corner case that most users probably won't run into (`tidy` and `error` are the only two chunks options of which the default values are modified by **rmarkdown**), and the workaround is relatively simple, so I wouldn't recommend using child Rmd or sourcing R scripts in each Rmd.

**Comment by cderv** [comment]
> This seems to be a corner case that most users probably won't run into (tidy and error are the only two chunks options of which the default values are modified by rmarkdown), and the workaround is relatively simple, so I wouldn't recommend using child Rmd or sourcing R scripts in each Rmd.

This confirms what I thought. Thank you ! 
I'll leave this opens in case anyone else wonder about this.

**Comment by turtlegraphics** [comment]
Apologies for not providing a MWE.  I really appreciate the help and the workaround.

**Comment by turtlegraphics** [comment]
I believe this same issue is affecting `knitr::knit_hooks$set(error = ...)`, since that also works for me if I put it in the .Rmd source but not if I put it in the `before_chapter_script`.

```
local({
  hook_old <- knitr::knit_hooks$get("error")  # save the old hook
  error_handler_function <- function(x, options) {
    # wrap x
    x <- paste(strwrap(x,76), collapse="\n## ")
    x <- paste(x,'\n',sep='')
    # pass the new x to the old hook
    hook_old(x, options)
  }
  knitr::knit_hooks$set(error = error_too_long_wrapper)
})
```

Is there an `options` workaround here as well?

**Comment by cderv** [comment]
Are you using the last version of **bookdown** ? 

This is working for me when I had this in `dummy.R`
```r
local({
  hook_old <- knitr::knit_hooks$get("error")  # save the old hook
  error_handler_function <- function(x, options) {
    # wrap x
    x <- paste(strwrap(x,76), collapse="\n## ")
    x <- paste(x,'\n',sep='')
    # pass the new x to the old hook
    hook_old(x, options)
  }
  knitr::knit_hooks$set(error = error_handler_function)
})
```

and this in `_bookdown.yml`
```yaml
before_chapter_script: dummy.R
```

and this is `01-intro.Rmd`
````markdown
```{r, error = TRUE}
# to be wrap by the hook
err <- sample(c("a", " "), size = 100, replace = TRUE, prob = c(0.8,0.2))
stop(paste0(err, collapse = ""))
```
````

All this is not really issues with **bookdown**. If you still have questions, please ask on one of the Q&A site: https://yihui.org/issue/#got-a-question

If you found a new issue, open a new one with a specific example to that issue. Having one topic per issue in Github is way easier for us. 

Thank you !
