### ISSUE TITLE
Figures and cross-references don't work in the KM mode

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#108]
If I put `new_session: yes` in the `_bookdown.yml` file, the figures and cross-references don't show up.

I am testing with a folder with `new_session: yes` in the `_bookdown.yml` file, a main file b.Rmd with
```
---
knit: "bookdown::render_book"
output:
  bookdown::pdf_book:
    keep_tex: yes
---
```
and one Rmd file with:

    # Lesson 1
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    ```
    ```{r cars}
    knitr::kable(summary(cars), caption="A cars table")
    ```
    You can also embed plots, for example:
    ```{r pressure, echo=FALSE, fig.cap="Plot of pressure vs temperature"}
    plot(pressure)
    ```
    You can see the cars in \@ref(tab:cars) and pressure in \@ref(fig:pressure)

This leads to a pdf with no figure or cross-references. If I comment out `new_session: yes`, it compiles fine with the figure and cross-references.

**Comment by yasirs** [comment]
@yihui do you know if the KM mode works for figures and cross-referencing, or am I doing something wrong?

**Comment by yihui** [comment]
The problem is that you don't have a _output.yml, and your second Rmd file does not have an `output` specification, so when it is knitted, bookdown has no idea what output you want. By default, the output will be HTML, which certainly won't work in your case. The solution is you do either of the two things I mentioned, and I'd recommend _output.yml.

**Comment by yasirs** [comment]
Yes, that fixed this issue. Thank you. Although I've run into some other issues on KM mode. I will open a different issue for it.
