### ISSUE TITLE
Missing metadata in published bs4_book

### ISSUE THREAD

**Issue by bwelman** [rstudio/bookdown#1080]
Only "title" and "author" are present as metadata in the published files. I'm missing "description".

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks. `description` metadata is not currently in the `bs4_book` html template. That is why it is not used. There is already a PR to add it (among others): https://github.com/rstudio/bookdown/pull/1034

**Comment by mccarthy-m-g** [comment]
Adding onto this, I was adding some bookdown books to my [Zotero](https://www.zotero.org) library using the Zotero Connector browser plugin and noticed that `bs4_book`s are not recognized as books by Zotero Connector (they're seen as a webpage). Whereas bookdown books using the default theme are recognized as books. I'm assuming this is due to differences in metadata between the two.

For example, compare [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) which uses the default `bookdown` theme (recognized as a book, see left icon from the Zotero Connector plugin):

![hands-on-programming](https://user-images.githubusercontent.com/51542091/111220626-0a0f4800-859f-11eb-872a-3965bddee117.png)

To [R4DS](https://r4ds.had.co.nz/index.html) which uses `bs4_book` (recognized as a webpage):

![r4ds](https://user-images.githubusercontent.com/51542091/111220628-0aa7de80-859f-11eb-9aa0-ddee883f479c.png)

It would be nice if the behaviour was consistent here between bookdown's different themes (assuming this is a bookdown issue and not a Zotero Connector issue).

**Comment by cderv** [comment]
@mccarthy-m-g that is interesting. Can you share more documentation about the zotero connector and what are the expected metadata ? thanks.

We'll definitely look into that soon.

**Comment by mccarthy-m-g** [comment]
@cderv Here is some [developer documentation](https://github.com/zotero/zotero-connectors#developing) for Zotero Connector. It looks like the plugin uses [Zotero Translators](https://www.zotero.org/support/translators) to identify whether something is a book, journal, webpage, etc. In this case I'd guess either an "Individual Site Translator" or "Metadata Import" is being used for classification.

I did a quick `command-F` search through the [current list of translators](https://zotero-translator-tests.s3.amazonaws.com/testTranslators.html#date=2021-03-15&browser=v&version=translation-server.SOURCE.8f2bf5e) for "gitbook" and "bookdown" but there were no hits. So maybe it is using metadata for classification.

Pinging the main contributor for Zotero Connector, @adomasven, as they might be able to identify the cause of [the discrepancy above](https://github.com/rstudio/bookdown/issues/1080#issuecomment-799755731) better than me.

**Comment by apreshill** [comment]
I think this is related to:

+ https://github.com/rstudio/bookdown/pull/1034
+ https://github.com/rstudio/bookdown/issues/1050
+ https://github.com/rstudio/bookdown/issues/1080

The Zotero Connector may rely on the meta tags to identify books. See: https://www.w3schools.com/tags/tag_meta.asp; https://ogp.me/#types



<img width="1395" alt="Screen Shot 2021-03-15 at 9 00 20 PM" src="https://user-images.githubusercontent.com/12160301/111240518-c4b83e00-85d1-11eb-9bc3-70889dedf98a.png">
<img width="1395" alt="Screen Shot 2021-03-15 at 9 00 32 PM" src="https://user-images.githubusercontent.com/12160301/111240527-c97cf200-85d1-11eb-82c2-6f44f092e76f.png">

**Comment by cderv** [comment]
We are working on adding metadata for `bs4_book` but I am still unsure which one are required for zotero connector. We'll add the main one and we'll see after merging is this is working for you or something is still missing.

**Comment by adomasven** [comment]
I missed the ping from earlier. See [exposing metadata](https://www.zotero.org/support/dev/exposing_metadata) for a dev guide on how to provide data that Zotero will understand.

**Comment by cderv** [comment]
Oh thank you ! 👍

**Comment by mccarthy-m-g** [comment]
Thanks for working on this! If you ping me after merging I'll check that the zotero metadata is working.

**Comment by cderv** [comment]
We've now merged the change. Using dev version and setting the correct variable in `index.Rmd` yaml should result in correct meta tag. 

Quick tests show that the zotero connector recognize it as bookdown. However, the content seen will depend of the book.
