### ISSUE TITLE
Images not rendering on gh-pages; might be missing some config step

### ISSUE THREAD

**Issue by lcolladotor** [rstudio/bookdown#1087]
Hi,

I'm using `bookdown` for https://github.com/lcolladotor/rnaseq_LCG-UNAM_2021 which I'm deplying through `gh-pages`. The images don't seem to be served by GitHub though, so this issue seems related to https://github.com/rstudio/bookdown/issues/133#issuecomment-252422207 and https://community.rstudio.com/t/troubleshooting-broken-images-in-bookdown-hosted-on-gh-pages/38441/6

At is one of the example `<img>`  https://github.com/lcolladotor/rnaseq_LCG-UNAM_2021/blob/ada473a744ebebe1cdcf0fd39b5a42d6c072b631/modelos-estad%C3%ADsticos.html#L470

```
<p><img src="_main_files/figure-html/filter_rse-1.png" width="672" /></p>
```

which does exist at https://github.com/lcolladotor/rnaseq_LCG-UNAM_2021/blob/ada473a744ebebe1cdcf0fd39b5a42d6c072b631/_main_files/figure-html/filter_rse-1.png yet it's not displayed in the final html. It might something to do with GitHub since https://lcolladotor.github.io/rnaseq_LCG-UNAM_2021/_main_files/figure-html/filter_rse-1.png returns a 404 error.

The original R code for generating the figure is https://github.com/lcolladotor/rnaseq_LCG-UNAM_2021/blob/94d0d7e9cc3c03ff0b0f7c38adffda359212ae20/05_modelos.Rmd#L27-L43 with the following YAML https://github.com/lcolladotor/rnaseq_LCG-UNAM_2021/blob/94d0d7e9cc3c03ff0b0f7c38adffda359212ae20/index.Rmd#L2-L14 for configuring the book.

Am I missing something here? Thanks!

Best,
Leo

R Session info: https://lcolladotor.github.io/rnaseq_LCG-UNAM_2021/index.html#r-session-information

**Comment by cderv** [comment]
The issue you encountered is because you did no configure gh-pages with a `.nojekyll` file as documented: https://bookdown.org/yihui/bookdown/github.html

This means you website on gh-pages will be processed by jekyll and so will ignore folder starting with `_`. 
This can be deactivated since 2009 : https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

As you are using the default book name `_main`, this will create a folder starting with underscore for assets. 
You can change the bookname too, but I would advice to use the .nojekyll file in your site as with the bookdown-demo book: https://github.com/rstudio/bookdown-demo/tree/gh-pages

This is mentioned in this issue in the https://community.rstudio.com: https://community.rstudio.com/t/broken-image-links-when-publishing-bookdown-on-github-pages/90897

I would advice to search in docs, Q&A websites and Issues when you encounter a problem. 

Did you try that already ? This is the documented way as shown in bookdown-demo example.

**Comment by lcolladotor** [comment]
Thanks for the answer. Using `.nojekyll` indeed solved my issue.

I did search for an answer across a few websites before asking my question. The keywords I used did not lead me to the answer you linked to. Whenever I try to find an answer and I don't locate it, I end up asking about it with as many details as possible. I don't ask without looking for an answer first though.

**Comment by cderv** [comment]
> https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports

Thanks for the feedback. We'll definitely try to make this information currently in the book https://bookdown.org/yihui/bookdown/github.html more findable in the future!

**Comment by apreshill** [comment]
One nice feature of the distill project templates is there is a checkbox for deploying to ghpages, which adds that for you. It might be nice to add to the bookdown template to help with discoverability (sorry @lcolladotor for the pain- this is a tricky one to troubleshoot for sure):

https://github.com/rstudio/distill/blob/5c62b3d13b4137343ada3c0dc3d2457a796a937c/inst/rstudio/templates/project/website.dcf#L11-L14

**Comment by cderv** [comment]
Thanks @apreshill ! That is a great idea! I'll look into that. 
Having helpers and templates inside the package to setup deployment (Addins or functions) could be really interesting in addition to better documentation !
