### ISSUE TITLE
images inside subdir are not carried into gitbook output

### ISSUE THREAD

**Issue by kmcbest** [rstudio/bookdown#1088]
If I organize my rmd files, along with their images, into subdirectories, I cannot get the image if I build to git_book. However, I can get them if I put pandoc_args --resource-path then build into Word_document2

master document (index.Rmd):

````gfm

---
title: "1"
author: "kmc"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site

output:
  bookdown::word_document2:
    number_sections: no
    toc: true
    toc_depth: 3
    pandoc_args: ["--resource-path", "part1"]
  bookdown::gitbook:
    toc_depth: 3
    config:
      toc:
        collapse: subsection
params:
  RootTitle: true
  Demand: false
  FeatureDesign: true
  TitleApp: true
---

# Firstly

```{r child=here::here("part1", "01.rmd")}
```

````

Child document (01.rmd):

````gfm

## Analysis

```{r echo=FALSE, fig.align = 'center', fig.cap = "research"}
knitr::include_graphics("rs.png")
```

````

This is an example which builds fine into word_document2 but the image is broken if built into git_book:

[bookdowndemo3.zip](https://github.com/rstudio/bookdown/files/6041842/bookdowndemo3.zip)

> xfun::session_info('bookdown')
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1, RStudio 1.4.1106

Locale:
  LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
  LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
  LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
  LC_NUMERIC=C                                                   
  LC_TIME=Chinese (Simplified)_People's Republic of China.936    

Package version:
  base64enc_0.1.3   bookdown_0.21     digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.2   
  grDevices_4.0.2   highr_0.8         htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1   
  markdown_1.1      methods_4.0.2     mime_0.10         rlang_0.4.7       rmarkdown_2.7     stats_4.0.2      
  stringi_1.5.3     stringr_1.4.0     tinytex_0.29      tools_4.0.2       utils_4.0.2       xfun_0.21        
  yaml_2.2.1       

---

By filing an issue to this repo, I promise that

- [X ] I have fully read the issue guide at https://yihui.org/issue/.
- [X ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
There are several layer of explanations to the behavior you are seeing: 

Child document will execute in the context of the main document, using working directory of the main document. This means that `knitr::include_graphics("rs.png")` which is in child doc will be ran in main doc so `rs.png` is expected to be relative to main doc. **knitr** will produce a syntax to insert image using this relative path `rs.png` - which is not really what you want. If you change to `part1/rs.png` in child document, it will work. 
This is currently the way **knitr** works: 
* For word it will produce in the md to be converted by Pandoc
````markdown
![(\#fig:unnamed-chunk-2)research](rs.png)
````
* For gitbook, it will produce HTML 
````html
<div class="figure" style="text-align: center">
<img src="rs.png" alt="research"  />
<p class="caption">(\#fig:unnamed-chunk-2)research</p>
</div>
````
Both are using relative path, to the main document, not to the child document. Hence why you would need to use `part1/rs.png`

With word document, the file will be embedded by Pandoc because docx will be self_contained. By providing `ressource_path`, you are telling Pandoc to look for the assets in a specific directory and not in the working directory (which is default behavior).

With gitbook, it does not work the same. The result of gitbook won't be self contained. So the HTML will be the one shown above, and the image will be look while viewing the HTML in relative to the output folder. However, the image is not found by **bookdown** in working directory (because it is in `part1/`), so it is not moved to output dir. If you move `rs.png` file to `_book`, it will show in your gitbook. 


Child document are inserted in the main document, so you need to set the correct path for assets. It is the case with `knitr::include_graphics()` but would be also if you were to use markdown syntax `![](img/path.png)` - `img/path` would need to be relative to the main document and not the child document. 

The issue here is not really as labelled - image in subdirs are carried out when the image path is correctly relative to the main document. This is the use of child document which is causing the behavior here. 

I would advice to use the correct relative path to your project in your child document. 
You may need last dev knitr version to avoid an error and the need to set `options(knitr.graphics.error = FALSE)` in your project.

Do you need to render child document on their own ? Are you using child document on their own without your main document ? Usually it is not for a bookdown project.

Also, does the above make sense ? Is the advice above useful ? 
Happy to discuss it further.

**Comment by kmcbest** [comment]
Thank you for the detailed reply. I've tried to add the subdir so it goes like 'part1/rs.png' (yes, I have to add error=FALSE to the call, I've read about that) and it works. In this approach I don't need to specify pandoc_args --resource-path anymore because the resource is in the right path, so it's better.

Your guess is right. I like to render my child documents seperately to check what it looks like, because it's tedious to comment/uncomment from the index.Rmd to include a single child document. Using the full path approach solves the problem of this issue, but breaks the portability of the child document. I think it would be beneficial to have multiple image search paths in the child documents, like latex's image path (see issue 230 https://github.com/rstudio/bookdown/issues/230  ). But that's another topic.

Cheers.





2255859@qq.com
 
From: Christophe Dervieux
Date: 2021-02-26 01:09
To: rstudio/bookdown
CC: kmcbest; Author
Subject: Re: [rstudio/bookdown] images inside subdir are not carried into gitbook output (#1088)
There are several layer of explanations to the behavior you are seeing:
Child document will execute in the context of the main document, using working directory of the main document. This means that knitr::include_graphics("rs.png") which is in child doc will be ran in main doc so rs.png is expected to be relative to main doc. knitr will produce a syntax to insert image using this relative path rs.png - which is not really what you want. If you change to part1/rs.png in child document, it will work.
This is currently the way knitr works:
For word it will produce in the md to be converted by Pandoc
![(\#fig:unnamed-chunk-2)research](rs.png)
For gitbook, it will produce HTML
<div class="figure" style="text-align: center">
<img src="rs.png" alt="research"  />
<p class="caption">(\#fig:unnamed-chunk-2)research</p>
</div>
Both are using relative path, to the main document, not to the child document. Hence why you would need to use part1/rs.png
With word document, the file will be embedded by Pandoc because docx will be self_contained. By providing ressource_path, you are telling Pandoc to look for the assets in a specific directory and not in the working directory (which is default behavior).
With gitbook, it does not work the same. The result of gitbook won't be self contained. So the HTML will be the one shown above, and the image will be look while viewing the HTML in relative to the output folder. However, the image is not found by bookdown in working directory (because it is in part1/), so it is not moved to output dir. If you move rs.png file to _book, it will show in your gitbook.
Child document are inserted in the main document, so you need to set the correct path for assets. It is the case with knitr::include_graphics() but would be also if you were to use markdown syntax ![](img/path.png) - img/path would need to be relative to the main document and not the child document.
The issue here is not really as labelled - image in subdirs are carried out when the image path is correctly relative to the main document. This is the use of child document which is causing the behavior here.
I would advice to use the correct relative path to your project in your child document.
You may need last dev knitr version to avoid an error and the need to set options(knitr.graphics.error = FALSE) in your project.
Do you need to render child document on their own ? Are you using child document on their own without your main document ? Usually it is not for a bookdown project.
Also, does the above make sense ? Is the advice above useful ?
Happy to discuss it further.

**Comment by kmcbest** [comment]
By the way, if I write "path/image.png" in my child files, I can never change the name of that directory. So there's no portability at all.

I think the solution is include_graphics("image.png") and let knitr insert the "path/" part on-the-fly when parsing the child file, then insert the content into the main document for rendering.

**Comment by cderv** [comment]
> I think the solution is include_graphics("image.png") and let knitr insert the "path/" part on-the-fly when parsing the child file, then insert the content into the main document for rendering.

To be more precise on how it works when you insert `child =` in option, It will run `knitr::knit_child()` and set the chunk option as knitr option for the `knit_child` rendering. `knit_child()` will be executed with the working directory of the main document. 

Here is a simple example of what happens: 
```r
> text <- c(
+     "## Analysis",
+     "`r getwd()`",
+     "",
+     '```{r echo=FALSE, fig.align = "center", fig.cap = "research"}',
+     'knitr::include_graphics("rs.png", error = FALSE)',
+     '```'
+ )
> 
> res <- knitr::knit(text = "`r knitr::knit_child(text = text)`", quiet = TRUE)
> xfun::raw_string(res)

## Analysis
C:/Users/chris/Documents/DEV_R/knitr

<img src="rs.png" title="research" alt="research" style="display: block; margin: auto;" />
> dir.create('dummy-knit-dir')
> res <- xfun::in_dir("dummy-knit-dir", 
+                     knitr::knit(text = "`r knitr::knit_child(text = text)`", quiet = TRUE)
+ )
> xfun::raw_string(res)

## Analysis
C:/Users/chris/Documents/DEV_R/knitr/dummy-knit-dir

<img src="rs.png" title="research" alt="research" style="display: block; margin: auto;" />
> 
> unlink("dummy-knit-dir", recursive = TRUE)
```

The child file is not really parsed, it is knitted as part of the main Rmd file, and the result is inserted in the placeholder.

Anyway, this is a knitr behavior and not really a **bookdown** issue. I'll think more if there is a solution that could help with this path thing when using child document 🤔

**Comment by kmcbest** [comment]
Thank you again, it's indeed a knitr's issue. I'll keep all the files in the main directory for the moment.

**Comment by quantitative-technologies** [comment]
> I would advice to use the correct relative path to your project in your child document.
> You may need last dev knitr version to avoid an error and the need to set `options(knitr.graphics.error = FALSE)` in your project.

@cderv I can't believe I had to find that info here! I spent a lot of time trying to figure out why `include_graphics` was telling me it couldn't find my file.
