### ISSUE TITLE
Spam/scam about bookdown

### ISSUE THREAD

**Issue by liutiming** [rstudio/bookdown#1106]
Hey this is not a technical issue, but just so you are aware bookdown is used for spam/scam...
![image](https://user-images.githubusercontent.com/39947942/111837794-51277100-88f0-11eb-8c29-df4b5f9a6245.png)

**Comment by yihui** [comment]
Thanks for the report! Unfortunately we cannot do much about it. I also receive this spam from time to time requesting to publish articles on my personal blog. I think the spammer just obtains your email address from a public web page and emails you.

The only thing you could do is probably hide your email address: https://pandoc.org/MANUAL.html#option--email-obfuscation

**Comment by liutiming** [comment]
Thanks! (not requesting any action from you!)

Quite interesting. So they must have used some kind of scraper to get emails?

**Comment by yihui** [comment]
Sometimes I can't imagine how much these spammers have learned about us. They send spams that appear to be relevant to you because they have been able to infer which web pages or domain names are associated with you (sometimes they also know your Github username, and LinkedIn/social media accounts, and [it feels a little scary](https://yihui.org/cn/2018/08/bridge-water/)).
