### ISSUE TITLE
LaTeX workflow fail when figure caption has &nbsp;

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/bookdown#1109]
Consider

``````
---
title: "Minimal Working Example"
author: "Raniere Silva"
date: "25/03/2021"
documentclass: article
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE, fig.cap = "Foo&nbsp;Bar", fig.align = 'center'}
plot(pressure)
```
``````

Compiling the previous document with `Rscript -e 'bookdown::render_book("mwe.Rmd", clean = FALSE)'` with fail and provide the following message

```
! Misplaced alignment tab character &.
<argument> ...hor \expandafter {\@currentHref }{\relax }}Foo&
                                                  nbsp;Bar\fi 
l.92 \caption{Foo&nbsp;Bar}
                         \label{fig:pressure}

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
```

The error is traced back to

``````
```{r pressure, echo=FALSE, fig.cap = "Foo&nbsp;Bar", fig.align = 'center'}
plot(pressure)
```
``````

that is being translated to

```
\begin{figure}

{\centering \includegraphics{_main_files/figure-latex/pressure-1} 

}

\caption{Foo&nbsp;Bar}\label{fig:pressure}
\end{figure}
```

## Proposed solution

Filter the value of `fig.cap` for expressions that might raise issues with LaTeX and others engines.

## Workaround (1)

Based on https://github.com/rstudio/bookdown/issues/558.

Users should use `\ ` instead of `&nbsp;`. For example,

```{r pressure, echo=FALSE, fig.cap = "Foo\ Bar", fig.align = 'center'}
plot(pressure)
```

## Workaround (2)

Users should use ` ` (`#xa0`) instead of `&nbsp;`. This is undesirable because is hard for users to input and might create some confusion in some users when reading.

## Non-effected Scenarios

If instead of

``````
```{r pressure, echo=FALSE, fig.cap = "Foo&nbsp;Bar", fig.align = 'center'}
plot(pressure)
```
``````

the document has

``````
```{r pressure, echo=FALSE, fig.cap = "Foo&nbsp;Bar"}
plot(pressure)
```
``````

The compilation will be successful. This happens because the code block will be transcript to Markdown instead of LaTeX. For clarification,

```
![(\#fig:pressure)Foo&nbsp;Bar](_main_files/figure-latex/pressure-1.pdf) 
```

instead of

```
\begin{figure}

{\centering \includegraphics{_main_files/figure-latex/pressure-1} 

}

\caption{Foo&nbsp;Bar}\label{fig:pressure}
\end{figure}
```

## Session Information

```
> xfun::session_info('bookdown')
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
  LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
  LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   bookdown_0.21     digest_0.6.27     evaluate_0.14    
  glue_1.4.2        graphics_4.0.2    grDevices_4.0.2   highr_0.8        
  htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1   
  markdown_1.1      methods_4.0.2     mime_0.10         rlang_0.4.10     
  rmarkdown_2.7     stats_4.0.2       stringi_1.5.3     stringr_1.4.0    
  tinytex_0.30      tools_4.0.2       utils_4.0.2       xfun_0.21        
  yaml_2.2.1 
```

**Comment by cderv** [comment]
To use in caption specific LaTeX character, you could use text reference feature: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references
> It is also useful when these captions contain special HTML or LaTeX characters, e.g., if the figure caption contains an underscore, it works in the HTML output but may not work in LaTeX output because the underscore must be escaped in LaTeX.

Example: 

````markdown
---
title: "Minimal Working Example"
author: "Raniere Silva"
date: "25/03/2021"
documentclass: article
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(ref:fig1) Foo&nbsp;Bar

```{r pressure, echo=FALSE, fig.cap = "(ref:fig1)", fig.align = 'center'}
plot(pressure)
```
````

The HTML character will be correctly converted by Pandoc before the LaTex -> PDF conversion. (converted to `Foo~Bar`, [tilde being a special character in LaTeX for non breakable space](https://en.wikibooks.org/wiki/LaTeX/Special_Characters))

Otherwise, your workaround 1 is the way to go for LaTeX output. 

You could also use the [non breaking space character](https://en.wikipedia.org/wiki/Non-breaking_space) in Markdown file using your keyboard (on windows it is ALT + 0160 for me). It should be ok for cross format (more than using HTML character in a LaTeX output). Still using the text reference feature or not. BTW using new Rmarkdown visual editor in 1.4 will help for such thing: https://rstudio.github.io/visual-markdown-editing/#/content?id=non-breaking-spaces (keyboard shortcut would be CTRL + SPACE with it)

I'll close this as I don't think there is anything more that **bookdown** can do with that.
