### ISSUE TITLE
Caching of Rcpp

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/bookdown#113]
This may 'just' be the known knitr issue ... but when examining Colin's draft book it seemed as if the Rcpp chunks were recompiled on each rebuild.  This would make writing an Rcpp-focused book somewhat slow and tedious.

Any hopes / plans / guesses / ... as to whether this may become improved upon?

**Comment by jjallaire** [comment]
I think this would rely on our changing sourceCpp to take an existing build
directory rather than creating it's own temporary build directory. Once
we've done that then knitr could create that build directory within the
cache directory and then pass it to us.

On Wed, May 11, 2016 at 7:52 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Well you may know just the guy to do it :grinning:

**Comment by jjallaire** [comment]
Indeed I am! :-)

On Wed, May 11, 2016 at 8:30 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by yihui** [comment]
Exactly. Dirk, I think I mentioned this issue to you at least twice in the past (I clearly remember that I mentioned it at useR 2014). The .so/.dll files are currently deleted after sourceCpp() is done, and we need to preserve them so we can reload them in future R sessions.

**Comment by eddelbuettel** [comment]
@yihui I have no doubt we talked about it, I doubt was able to offer solutions.  

FWIW I just played with it trying to set `TMP` and `TEMPDIR` from within the running R session. No mas...  But then I guess we knew that. Luckily we may both know the guy to fix all this :grinning:

**Comment by coatless** [comment]
Any ETA on when this proposed change is likely?

**Comment by coatless** [comment]
@jjallaire Is there anyway I could help bring this feature forward? 

After a quick glance of the `Rcpp` attributes source, naivety, and the desire for this feature, it seems like the problem of the `.so/.dll` files being removed is due to the `rebuild` flag triggering the `--preclean` option during the `R CMD SHLIB` stage of `sourceCpp()`.

https://github.com/RcppCore/Rcpp/blob/blob/2a33dccca5a6fc0a4b86525da215a8a4c71e0eae/R/Attributes.R#L116

Also, it seems that the current operation regarding `sourceCpp()` is to evaluate the file in place instead of creating a copy of the cpp file and placing into the R session's `tempdir()`:

https://github.com/RcppCore/Rcpp/blob/2a33dccca5a6fc0a4b86525da215a8a4c71e0eae/R/Attributes.R#L43

Briefly looking at the C++ backend of `sourceCpp()`, it looks like there is support for saving file locations:

`sourceCppContext()`:
https://github.com/RcppCore/Rcpp/blob/2a33dccca5a6fc0a4b86525da215a8a4c71e0eae/src/attributes.cpp#L3163-L3221

`class SourceCppDynlib`:

https://github.com/RcppCore/Rcpp/blob/2a33dccca5a6fc0a4b86525da215a8a4c71e0eae/src/attributes.cpp#L2817-L3093

**Comment by jjallaire** [comment]
I'm afraid I'm the right person to make this happen. I'm planning on
tackling this relatively soon after useR.

**Comment by jjallaire** [comment]
Documentation on using the new Rcpp caching and chunk consolidation features are here: http://rmarkdown.rstudio.com/authoring_knitr_engines.html

**Comment by eddelbuettel** [comment]
Just wanted to say *totally awesomesauce*.

 I just used that in knitr/rmd/rcpp/python mashup for JSM for tomorrow.  Thanks, @jjallaire and @yihui !

**Comment by jjallaire** [comment]
Excellent! BTW we've been working hard on integrating a new SQL engine
(based on DBI connections) end-to-end which for some audiences will be a
nice addition.
