### ISSUE TITLE
127.0.0.1:20866: /rmd_output/3/Writing%20 not found

### ISSUE THREAD

**Issue by lennyleadership** [rstudio/bookdown#1130]
I wanted to export the book to pdf, but I got the error message.

Note: Writing%20 would be related to my project name.  The full name is "Writing #01_Interview Prep"

**Comment by cderv** [comment]
Hi, 

Thanks for opening an issue. Please follow the issue guide: https://yihui.org/issue/
We need more information on what you are trying to do and about your project. 

When you mean export to PDF, do you mean build the book to LaTeX then PDF using the `bookdown::pdf_book` format ? 
Or do you mean print the book to PDF ? 

What is `127.0.0.1:20866: /rmd_output/3/Writing%20`? URL of the book when you run preview the book ?

We need more information so that you help us help you. Thank you.

**Comment by lennyleadership** [comment]
Sorry, I am quite new to bookdown, so I did not use the appropriate word to get what I was doing across to you.  After clicking the knit button.  I have a view.  There are two choices, PDF and EPUB when I hovered on the 'download' menu.  I chose 'PDF', then I got this error message.

**Comment by cderv** [comment]
Oh ok. Thanks for the precision. You need to generate the book in PDF and EPUB format before being able to download them. 

You can build all format using the Build button or `render_book(output_format = "all")`

The bookdown book is the place to start to know more: https://bookdown.org/yihui/bookdown/output-formats.html
The download menu is mentionned in : https://bookdown.org/yihui/bookdown/html.html#gitbook-style

So you need to create the files first. Did you do that ? Are they in the output directory ?

**Comment by lennyleadership** [comment]
Alright.  Thank you for being patient.
