### ISSUE TITLE
diacritical problems with bs4_book

### ISSUE THREAD

**Issue by bwelman** [rstudio/bookdown#1135]
I just noticed that diacritical character don't display properly with bookdown (0.21.7) and bs4_book output. Three weeks ago everything was ok. The gitbook output is ok. Updated to bookdown 0.21.10, still problems. And also with a new book.

**Comment by cderv** [comment]
Do you have an example to share so that we can look into ?

This is possibly related to https://github.com/rstudio/bookdown/issues/1015

I can reproduce on my French computer by inserting this in `02-literature.Rmd` of bookdown-demo

```markdown
# Literature

Inserting special chars: âöõäéè
```

Leading to 
![image](https://user-images.githubusercontent.com/6791940/114701314-efa5c700-9d22-11eb-8beb-9c1e5d371f91.png)


The HTML content is 
```html
<p>Inserting special chars: Ã¢Ã¶ÃµÃ¤Ã©Ã¨</p>
```

**Comment by bwelman** [comment]
If necessary I can send an example, but I get exactly the same result as you with bookdown-demo on my Dutch computer. I'll take a look at the related issue.

**Comment by bwelman** [comment]
Installing bookdown#1027 solves the problem. Everything ok now. Thanks.

**Comment by cderv** [comment]
Thanks that is good to know !
