### ISSUE TITLE
I can only create html output, no pdf or word

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#119]
I can only see html, but no pdf or word. I'm using windows and RStudio latest version. When I try to render the book with either bookdown::render_book() or preview_chapter(), the LaTeX file seems to be created fine, but the pdf or word output is either not created or incomplete.
With render_book(), I get an error saying

Error: Failed to compile RPoE.tex.
In addition: Warning messages:
1: In FUN(...) :
  Perl must be installed and put on PATH for latexmk to work
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "RPoE.tex"' had status 1 
> 

Here is a screen shot:
 
![image](https://cloud.githubusercontent.com/assets/10256096/15403703/85b9fb26-1db7-11e6-8356-5bc8271340aa.png)

**Comment by ccolonescu** [comment]
It apparently has to do with not finding the figure files, although the html version renders them correctly.

**Comment by ccolonescu** [comment]
I located the error at a knitr::include_graphics() line.  MiKTeX does not know where to look for the PNG figure. I still don't know how to fix this.

**Comment by yihui** [comment]
Can you just open RPoE.tex and compile it to PDF? I need to see the actual error message.

**Comment by ccolonescu** [comment]
Here is the LaTeX session. The figures generated in R are OK, but the external one does not show.
![image](https://cloud.githubusercontent.com/assets/10256096/15452385/1c848554-1fab-11e6-99f1-87a7c39dcd09.png)

**Comment by ccolonescu** [comment]
Apparently MikTex looks for figures in a file "/figures-latex" which does not exist. I created this file manually, which fixed the R-generated figures, but it does not work for the external one.

**Comment by ccolonescu** [comment]
Here is the part hat makes trouble:
![image](https://cloud.githubusercontent.com/assets/10256096/15452462/79e06622-1fac-11e6-8f35-bd1a9c298afa.png)

**Comment by ccolonescu** [comment]
This is a closeup of the errors in my other screen shot:
![image](https://cloud.githubusercontent.com/assets/10256096/15452491/2d9e8f9a-1fad-11e6-98cc-be4b347d1312.png)

**Comment by yihui** [comment]
Okay I see. I think the absolute path is the culprit. You should almost always use relative paths everywhere (and forward slashes instead of backslashes in paths). I don't recommend you to put your own images under `_bookdown_files` -- this directory is supposed to contain the automatically generated R plots. If the figure is not automatically generated from R code, you should put it in a different directory, otherwise you should probably just let R generate it instead of using `knitr::include_graphics()` (perhaps you have a reason for doing the latter).
