### ISSUE TITLE
Conditionally add Theorems and Proofs env using Fenced div syntax

### ISSUE THREAD

**Issue by tchevri** [rstudio/bookdown#1232]
Hi,
Thank you so much for help with https://github.com/rstudio/bookdown/pull/940 and https://github.com/rstudio/bookdown/issues/924. can't thank you enough!

with the previous syntax, I could write things such as:
   ` ```{proof, eval = (out_type=="beamer"), echo=(out_type=="beamer")}`
   ` ``` `
or conversely
   ` ```{proof, eval = (out_type!="beamer"), echo=(out_type!="beamer")}`  
   ` ``` `

Would it be possible to request this be available with the new fenced div syntax?

many thanks
thomas

**Comment by tchevri** [comment]
If I may add a quick note (somewhat unrelated, I guess), I see that `remark` is also well implemented now.
It works without issues when compiling `github` book
However, when i tried with `bookdown::beamer_presentation2`, I get `! LaTeX Error: Environment remark undefined.` 
Is this behavior expected or do i need to do something else?
many thanks thomas

**Comment by cderv** [comment]
Hi @tchevri ! 

Thanks for reaching out with those two questions. 

About the first one, have a look to the `asis` engine : https://bookdown.org/yihui/rmarkdown-cookbook/eng-asis.html
It allows you to add some Markdown content conditionally. 
In your case, this should be 
````markdown
```{asis, echo= knitr::pandoc_to("beamer")}
::: {.proof}
Content of the proof
:::
```
````

Regarding the second question, beamer has special treatment because it defines some environment already but not all. See the release note of last 0.23 release: https://pkgs.rstudio.com/bookdown/news/index.html#new-features
Look for `beamer_presentation2` in one of the bullet point. 

**bookdown** won't define environment for you so only the one provided with beamer can be used as-is. The others needs to be defined by the user itself. 

Does that answer your questions ?

**Comment by tchevri** [comment]
Thank you so much!! It totally does - could I please totally abuse your kindness and ask a follow up question in order to better understand how to use this new custom `fenced div` environment?
Say I have some text such as:

- Multiplication
    + Matrices are multiplied by using the inner product.  
::: {.definition}
A set\index{set} is a well-specified collection of element.  
$\forall A$, we write $a\in A$ to indicate that $a$ is a member of $A$.  
:::
    + blabla - sorry my example a bit random here....

Is there a way to get the definition inside the list?
In pure LaTeX, it's fairly straightforward.
I am not sure how it's done exactly with Rmarkdown, the format used for bookdown.
I looked at https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html but there are no examples.
The `asis` technique you mentioned (also mentioned here: https://tex.stackexchange.com/questions/210003/how-can-i-nest-a-code-chunk-within-an-enumerate-environment-when-using-r-markdow) doesn't seem to help.
I have tried with many permutations of spaces, but didn't seem to do it.

So sorry to trouble you with this - maybe others will stumble on this too?
many thanks
thomas

**Comment by cderv** [comment]
> Is there a way to get the definition inside the list?

We are using Pandoc feature called Fenced Div and I am not sure that the Markdown syntax allows to use Fenced div syntax inside a bullet list. 

> In pure LaTeX, it's fairly straightforward.

The Markdown syntax is supposed to be cross format and it creates a div in HTML. I am not sure if this would be possible to write this as a `<div>` inside `<ul>` and `<li>`. 

For this, you may not need to use the special syntax. You can also write directly raw code for what you want to do. If LaTeX is the only output format, you can use raw LaTeX. 

Anyway, How would you write that in LaTeX ?
