### ISSUE TITLE
section label fails in bookdown::html_document2 when having both pandoc identifiers and classes

### ISSUE THREAD

**Issue by qiushiyan** [rstudio/bookdown#1234]
According to https://pandoc.org/MANUAL.html#extension-header_attributes, we should be able to use `{#identifier .class}` syntax for section headers. Though section label does not work when having additional classes

Example 

```
---
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Preface {#something .unnumbered}

cross reference \@ref(something) will not work
```

screenshot 

![image](https://user-images.githubusercontent.com/48123899/130182972-984e89fe-fb64-44d2-b1cd-7d4ad5dc0372.png)

The HTML div element containing section header will not get an `id='something'` attribute.

**Comment by cderv** [comment]
This is because you use the `.unnumbered` class and this will lead to an unnumbered header. **bookdown** reference mechanism works only with numbered header. Referencing a header label is supposed to generate something like `Section 1.1`, but without number, it can't do that. 

Cross referencing mechanism needs support for other style of reference. There are related feature request for that: #74, 

For unnumbered header, you will need to use text based link as detailed in here https://bookdown.org/yihui/bookdown/cross-references.html

```markdown
---
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Preface {#something .unnumbered}

cross reference will work: See [Preface](#something)

````

Hope it helps

**Comment by qiushiyan** [comment]
Thank you for the explanation.
