### ISSUE TITLE
[FR] toc_toggle option 

### ISSUE THREAD

**Issue by cansavvy** [rstudio/bookdown#1251]
It sounds like you can't just turn off the sidebar TOC according to the manual?: 
https://bookdown.org/yihui/bookdown/html.html

> There are a few arguments of html_document() that have been hard-coded in gitbook() and you cannot change them: toc = TRUE (there must be a table of contents), 

We have a use case where we need to link to individual chapters one at a time _without_ confusing our users by having the TOC on the side -- we don't want them to use that for navigation. 

I found this [StackOverflow post](https://stackoverflow.com/questions/57713191/remove-table-of-contents-from-a-r-bookdown-to-pdf-book-or-pdf-document2) and providing arguments like it in an `_output.yml` file but always got a message like: 
```
Error in config[["collapse"]] : subscript out of bounds
```
Presumably because TOC collapse option (and perhaps other TOC-related options) are being set anyway?

I would love to be able to just turn off the sidebar TOC completely by providing a `toc = FALSE` argument somewhere. 

But secondarily, if there's a way to just have the sidebar TOC tucked away upon a using the url, that would work for our use case as well. 

If there IS a way to get rid of the TOC easily, then I would be delighted to know how to do that. 

### More context on the use case: 

We are trying to post our bookdown rendered course on Coursera in a way that requires minimal maintenance of multiple copies of the course but Coursera is organized by chapters. 

But Coursera would like a link to each chapter: 

![coursera_attempt](https://user-images.githubusercontent.com/23458084/131910515-ccafc022-bacb-4494-8c36-555259426af8.png)
![plugin](https://user-images.githubusercontent.com/23458084/131910523-d4e60cc3-27c3-46fd-a890-16a709b0fed9.png)

We like our bookdown course that is living on the Github pages and would like it to maintain the same aesthetics and structure and ideally want maintenance to be streamlined (don't want to make a bunch of copies of the same material. But I don't know Java and CSS in order to make this happen) and we just need the TOC gone. 

This is my [original issue](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/174), but it has other non-related info on it so maybe its not super informative.

**Comment by Pindar777** [comment]
@cansavvy You can add these lines to your css and the issue should be solved

```
.book .book-body .page-wrapper .page-inner {
  max-width: 100% !important;
}

.book.with-summary .book-header.fixed {
    left: 0%;
}

.book.with-summary .book-body {
    left: 0%;
}

.book.with-summary .book-summary {
    width: 0%;
}

.book-body.fixed > div > .book-header.fixed > a:nth-child(1) {
  visibility: hidden;
}

```

**Comment by cderv** [comment]
`toc` can't indeed be set to TRUE in `gibook()` or `bs4_book()` output. This is because book-like output are supposed to have a TOC for navigation, and they are special website build for linear navigation using a TOC. 

If you need a website without a TOC for navigation, you could use another type of website with another way to navigate. **blogdown** or R Markdown Website are some options with Rmd files. 

However, you could indeed tweak the `gitbook()` output by hiding the element you don't want. They will be there in the source, but not shown in the browser. The code above by @Pindar777 should do the trick (but will probably change the sizing from what I could see) 

If you want to just hide the TOC by default as when you click on the collapse TOC button, you can add this JS part in your index.Rmd file (if your are using `new_session: true`, you probably need to add this as a common config in each file, or as HTML `script` element directly in an included header file.)

````markdown
```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```
````

This will hide the sidebar by default. You could also add a CSS to hide the toggle button, or even use some JS to remove the toggle button if you don't want it. (but it will be hard to navigate I guess)

We could probably offer a gitbook configuration for this 🤔 . Currently, the sidebar will be open by default and when hidden by the user, it will stay hidden until toggled on. 

> But secondarily, if there's a way to just have the sidebar TOC tucked away upon a using the url, that would work for our use case as well.

There is no a url parameter to use to achieve this. 



Does that help you ? Is this what you are looking for ?

**Comment by cansavvy** [comment]
Yes! Thank you @cderv and @Pindar777  for these solutions! This should work. Will try implementing these. Much appreciated!

**Comment by cderv** [comment]
Great! 

CSS and JS will allow you to tweak the output. If you want to customize the source of output to not have a browser only solution, you could also try to post process the result. 

Anyway, hope it will work. Keep us updated!

**Comment by cansavvy** [comment]
Those CSS lines worked perfectly! Thank you!

**Comment by Pindar777** [comment]
@cansavvy Great :-)
