### ISSUE TITLE
Publishing bookdown website from markdown editors

### ISSUE THREAD

**Issue by yiugn** [rstudio/bookdown#1257]
The bookdown library is the best library I've ever experienced. However, there is one drawback, that to make a book with the bookdown library, you have to use an IDE like rstudio and use the cumbersome way of uploading it to the server. Of course, this is not a difficult method requiring very specialized knowledge, but there is no denying that it is quite cumbersome. This is what is preventing the bookdown library from becoming popular.

The method I would like to suggest is to write through a markdown-only note app such as Joplin and upload it through it easily. This method is similar to the method of writing and saving an article through the blog editor and uploading it directly to the blog.

How about launching a project of making a markdown-based note program such as Joplin,  and directly publishing in the form of bookdown?

**Comment by cderv** [comment]
Hi ! 

Thanks for opening the discussion ! 

I'll try to explain about **bookdown** first than point you to a new alternative.

**bookdown** is an R package which requires at least R to work. However, RStudio IDE is not needed, and using R code inside the book is not needed either. You can use any IDE or editor you like to write `.Rmd` files containing only markdown syntax without code.  
RStudio IDE only has features integrated to work nicely with **bookdown** project, and it could feel more natural when using with R. 

**bookdown** is first designed to write `.Rmd` files which contains Code + Markdown syntax, but I believe it can work with plain `.md` file by specifying them in `rmd_files` config. then Pandoc only would be use to convert to HTML without requiring any knitting. 

So writing markdown only content is possible, and you would just need R to do the conversion in HTML. It could be run at command line once installed and in your PATH. Using makefile, bash script or anything, I believe you can convert a **bookdown** project written with any tool to a HTML product. 

**bookdown** will produce HTML folder with all the content, and you can publish anywhere that serve HTML file. Unfortunately, I did not get the point related to 
> and use the cumbersome way of uploading it to the server.

Can you give detail ? 

That being said, you may not be an R user in the first place, and you may not be comfortable with the R requirement that **bookdown** have (as an R package). Especially if you don't need it. This will not change, **bookdown** will still require R in the future, and will still be designed to work with Rmd in the first place. 

However, there is a new project called Quarto (https://quarto.org/) which is more generic. I suggest you give it a try. Specifically because it has a book format which has been rethink and Quarto is not tied to R: https://quarto.org/docs/books/. You only need to install the quarto cli tool then write `.md` file (or `.qmd` file if you need a computation engine) - You can work with any IDE which has markdown editor, but again RStudio IDE has already a nice integration (in daily or preview version).

It still in an early development project but it is already working well. I believe Quarto would answer your concern, and if not, we would try to meet the need there. 

Hope it helps
