### ISSUE TITLE
bookdown::bs4_book errors if chapter contains period

### ISSUE THREAD

**Issue by robitalec** [rstudio/bookdown#1263]
## Bug

I had trouble using the bookdown::bs4_book() format when one of my chapters had a period in it. Eg. in a book with description of packages, we might have chapters named "data.table" "broom.mixed" etc, or some other totally unrelated reason for a period in a title. Note this didn't error when I had space between the period and the words eg. "data . table".

This is happening after the book is rendered, in the "Tweaking xyz chapter" step. 

## Reproducing

With a fresh project, use the example bs4_book. Add another Rmd with some chapters titled "ggplot2", "bookdown", "data . table", "data.table".

```r 
bookdown::create_bs4_book('.')
writeLines('# ggplot2 \n\n# bookdown \n\n# data . table \n\n# data.table', '08-packages.Rmd')
bookdown::render_book()
```
```
[...]
output file: 08-packages.knit.md

/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS try-bookdown-period.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output try-bookdown-period.html --lua-filter /home/alecr/R/x86_64-pc-linux-gnu-library/4.1/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/alecr/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/alecr/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/RtmpeTSuz3/file129ba4f8ffcc5 --wrap preserve --standalone --section-divs --template /home/alecr/R/x86_64-pc-linux-gnu-library/4.1/bookdown/templates/bs4_book.html --highlight-style pygments --number-sections --css style.css --include-in-header /tmp/RtmpeTSuz3/rmarkdown-str129ba179ab9fd.html --mathjax --citeproc 
Tweaking _book/index.html
Tweaking _book/hello-bookdown.html
Tweaking _book/cross.html
Tweaking _book/parts.html
Tweaking _book/footnotes-and-citations.html
Tweaking _book/blocks.html
Tweaking _book/sharing-your-book.html
Tweaking _book/references.html
Tweaking _book/ggplot2.html
Tweaking _book/bookdown.html
Tweaking _book/data-.-table.html
Tweaking _book/data.table.html
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... bs4_chapter_tweak -> <Anonymous> -> read_utf8 -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file '_book/data.table.html': No such file or directory
Calls: <Anonymous> ... bs4_chapter_tweak -> <Anonymous> -> read_utf8 -> readLines -> file
```

`_book/data.table.html` doesn't exist, `_book/data.html` does. 
Ballpark [here](https://github.com/rstudio/bookdown/blob/main/R/bs4_book.R#L260), haven't had time to pin it exactly. Not urgent - a simple fix is to remove the period... 
Thanks! 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('bookdown')` in your issue?

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux, RStudio 1.4.1716

Locale:
  LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
  LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
  LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3      bookdown_0.24.1      bslib_0.3.1          cli_3.0.1           
  digest_0.6.28        ellipsis_0.3.2       evaluate_0.14        fastmap_1.1.0       
  fs_1.5.0             glue_1.4.2           graphics_4.1.1       grDevices_4.1.1     
  highr_0.9            htmltools_0.5.2.9000 jquerylib_0.1.4      jsonlite_1.7.2      
  knitr_1.36           lifecycle_1.0.0      magrittr_2.0.1.9000  methods_4.1.1       
  R6_2.5.0             rappdirs_0.3.3       rlang_0.4.11.9001    rmarkdown_2.11.3    
  sass_0.4.0.9000      stats_4.1.1          stringi_1.7.5        stringr_1.4.0.9000  
  tinytex_0.34         tools_4.1.1          utils_4.1.1          vctrs_0.3.8         
  withr_2.4.2          xfun_0.26            yaml_2.2.1          
```

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?

**Comment by cderv** [comment]
Thanks for the report. 

This is indeed an odd bug which is well hidden in our process. 

When file is split, the name will be taken from chapter id by default. So in your example `data.table`. 
Then, it will go through this line to have the name of the corresponding html file
https://github.com/rstudio/bookdown/blob/7ce6dc65b39ffe846e2ff88c160a69f2348a5a92/R/html.R#L413
but 
``` r
xfun::with_ext("data.table", "html")
#> [1] "data.html"
```
It is why the filename created is not the same name as the chapter id. 

Workaround for you without changing much: add an id to the chapter without a `.`
````markdown
# data.table {#data-table}
````

You could also split differently (`split_by` option)

However, on our side, we could handle this better. We do this because when `split_by = "rmd"` is used, we need to replace `.Rmd` by `.html` and not just append `.html`. 

I'll think of something 🤔

**Comment by cderv** [comment]
I guess we would need to do something like this 
```diff
diff --git a/R/html.R b/R/html.R
index a5b04d88..ccb86663 100644
--- a/R/html.R
+++ b/R/html.R
@@ -374,6 +374,7 @@ split_chapters = function(
       idx = next_nearest(idx, grep('^<div', html_body))
       idx = c(1, idx[-n])
     }
+    nms = basename(with_ext(nms, '.html'))
   } else {
     h1 = grep('^<div (id="[^"]+" )?class="section level1("| )', html_body)
     h2 = grep('^<div (id="[^"]+" )?class="section level2("| )', html_body)
@@ -405,12 +406,12 @@ split_chapters = function(
     if (identical(with_ext(head(nms_chaps, 1), ''), 'index')) nms[1] = 'index'
     html_body[idx] = ''
     idx = idx2
+    nms = basename(paste0(nms, ".html"))
   }
   if (n == 0) {
-    idx = 1; nms = output; n = 1
+    idx = 1; nms = basename(output); n = 1
   }

-  nms = basename(with_ext(nms, '.html'))  # the HTML filenames to be generated
   input = opts$get('input_rmd')
   html_body = add_chapter_prefix(html_body)
   html_toc = restore_links(html_toc, html_body, idx, nms)
```

* if `use_rmd_names == TRUE` then `nms` will be the Rmd filename. So we should replace extension .Rmd by .html
* otherwise, `nms` will be derived from chapters `id` inside HTML file. In that case we can make the assumption that it would not contain any extension and we can paste HTML 
* Special edge case of no chapter so no split means `nms = output` and in that case, extension will already be HTML

This would be a coherent fix where HTML filename is supposed to be derived from id of the chapter. Which is clearly wrong here.

However, problem I see is that changing this could break user of `gitbook()` because if they rebuild, filename would be different and possible link to other file would break. If they correctly use cross reference it should work so I think it is good but maybe shared link on the web would fail. 

Does the possible breakage justify the fixing ? 
Or should we live with this as there is an manual workaround by using an id ? 
e.g with your previous example
````r
writeLines('# ggplot2 \n\n# bookdown \n\n# data . table \n\n# data.table {#data-table}', '08-packages.Rmd')
````

@yihui do you have some thoughts ?

**Comment by robitalec** [comment]
Ya it feels like a pretty minor issue, not worth breaking other things. 

Adding an id to the header is a good solution - I had just removed the period altogether. It's not like that period is doing any work in _communication_. 

I was surprised to see it because it only happened when I switched from from gitbook to bs4_book. Thankfully, I could intuit from it breaking on the data.table chapter, that it was likely from the period. Is there somewhere the `Tweaking chapters ...` processing is documented? Maybe we could just include some mention of this there, since having a heads up in the docs might help someone reach the manual id solution. 

Thank you @yihui and @cderv for the help and the package!
