### ISSUE TITLE
Error: C stack usage is too close to the limit

### ISSUE THREAD

**Issue by psads-git** [rstudio/bookdown#1290]
I have the following  R chunk, which works fine if I run it. However, when I knit it, I get the error:

`Error: C stack usage is too close to the limit`

If I knit it without `cache = T`, it works well.

Thanks in advance!

````
```{r cache=FALSE}
library(tidyverse)
library(gganimate)
library(gifski)

df <- data.frame(
  event = 1:10,
  angle1 = seq(0, pi/4, length.out = 10),
  angle2 = seq(0 + pi, pi/4 + pi, length.out = 10),
  angle3 = seq(pi/2, pi/2 + pi/4, length.out = 10),
  angle4 = seq(3*pi/2, 3*pi/2 + pi/4, length.out = 10)
)

p <- ggplot(df, aes(x = 0, y = 0, radius = 5)) +
  geom_spoke(aes(angle = angle1), color="blue") +
  geom_spoke(aes(angle = angle2), color="blue") +
  geom_spoke(aes(angle = angle3), color="blue") +
  geom_spoke(aes(angle = angle4), color="blue") +
  geom_point(aes(x=1, y=1), color="red", size=3) +
  coord_cartesian(xlim = c(-1,1), ylim = c(-1,1)) +
  theme(legend.position = NULL, aspect.ratio = 1) +
  transition_states(event, wrap = F) +
  enter_grow() +  ease_aes('linear') + exit_shrink()

animate(
  p, width=700, height=700, res=150, duration = 8,
  fps = 20, renderer = gifski_renderer(), start_pause = 20,
  end_pause = 120)
```
````

**Comment by cderv** [comment]
Hi, 

Thanks for the report.

This is probably not an issue specific to **bookdown** if you think it is related to caching. I can reproduce by only using `knitr::knit()` on a file with this content. 

@yihui is there some limitation on what the chunk content could be ? The objects in this chunk could be quite complex. 
However, we are using a R Base mechanism for the caching so not sure if there is an issue at deeper level maybe. 🤔 

@psads-git there is since recently another caching mechanism more explicit: https://bookdown.org/yihui/rmarkdown-cookbook/cache-rds.html

As a workaround, you may used that instead and see if it works. 

Thanks for the report.

**Comment by psads-git** [comment]
Thanks, Christophe, for your answer and help! I have tried the new method you suggested and it works perfectly: Fast and no error anymore!

**Comment by yihui** [comment]
> is there some limitation on what the chunk content could be ?

I'm not sure. It might be related to lazy loading of cache. You may try the chunk option `cache.lazy = FALSE`.
