### ISSUE TITLE
Animation is not rendered with suppressMessages(library(tidyverse))

### ISSUE THREAD

**Issue by psads-git** [rstudio/bookdown#1291]
I have the R chunk below. If I uncomment any of the commented lines of code, the animation is not rendered.

Thanks in advance!

```
```{r echo=TRUE}
xfun::cache_rds({
# suppressMessages(library(tidyverse))
# options(tidyverse.quiet = TRUE)
library(tidyverse)
library(gganimate)
library(gifski)

df <- data.frame(
  event = 1:10,
  angle1 = seq(0, pi/4, length.out = 10),
  angle2 = seq(0 + pi, pi/4 + pi, length.out = 10),
  angle3 = seq(pi/2, pi/2 + pi/4, length.out = 10),
  angle4 = seq(3*pi/2, 3*pi/2 + pi/4, length.out = 10)
)

p <- ggplot(df, aes(x = 0, y = 0, radius = 5)) +
  geom_spoke(aes(angle = angle1), color="blue") +
  geom_spoke(aes(angle = angle2), color="blue") +
  geom_spoke(aes(angle = angle3), color="blue") +
  geom_spoke(aes(angle = angle4), color="blue") +
  geom_point(aes(x=1, y=1), color="red", size=3) +
  coord_cartesian(xlim = c(-1,1), ylim = c(-1,1)) +
  theme(legend.position = NULL, aspect.ratio = 1) +
  transition_states(event, wrap = F) +
  enter_grow() +  ease_aes('linear') + exit_shrink()

animate(
  p, width=610, height=610, res=150, duration = 8,
  fps = 20, renderer = gifski_renderer(), start_pause = 20,
  end_pause = 120) -> res
res
})
```
```

**Comment by psads-git** [comment]
Now, even keeping those two lines commented, the animation is _not_ rendered at all. Thanks!

**Comment by cderv** [comment]
You should read https://bookdown.org/yihui/rmarkdown-cookbook/cache-rds.html and try to understand how `cache_rds()` is working. 

Especially this sentence 
> The biggest disadvantage of xfun::cache_rds() is that it does not cache side effects (but only the value of the expression), whereas knitr does.

So you'll probably want to only cache the time consuming step and not the whole code. (probably the last part only when calling animate and setting `hash` to global values it depends on. 

Also, you probably don't want to cache the library loading step otherwise next time you'll run, it will load the cache and not run the code meaning library won't be loaded. 

Those are not **bookdown** issues and more like generic questions. Please follow the issue guide: https://yihui.org/issue/#got-a-question

**Comment by psads-git** [comment]
Thanks, Christophe, for your useful answer! Now, by putting into `cache_rds()` only the time-consuming code, it works perfectly -- and now, thanks to your clarification -- I know why.
