### ISSUE TITLE
New and disturbing span after part

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/bookdown#1326]
Hi!

In the book I use the standard PART-s injection: `# (PART) MYPART {-}`

Having updated somewhere today, I saw in the book these span, which did not exist before.

I can't figure out where they came from. They remain even if I remove my css or go back to previous versions of bookdown.

Please fix/tell me how to remove this span

Thanks!

![image](https://user-images.githubusercontent.com/52919010/161939686-67235f84-f592-410f-ba4f-9669a7bc364e.png)

**Comment by cderv** [comment]
Hi, 

Thanks for the report. I could reproduce from your description and I know where this came from now. 
You can add `anchor_sections: false` to as configuration for `gitbook()` to avoid this for now. 

Also, on a side note, please next time avoid using works like _monstruous_ or _this crap_ as this is not really appropriate in the context of collaborations here. It does not add anything to the facts to help and it is not pleasant to read as maintainers. Thank you for your understanding.

**Comment by cderv** [comment]
For context, this happens because of the `anchor_sections` feature, which adds a link with no text content in each header so that we can insert a logo or a text using CSS.

Pandoc will process each header to put it into TOC, and convert the reference links found into it `<a></a>` to a `<span></span>`, but as not content in the link, the span is empty. 

However, this is not causing any issue whatsoever and I was thinking this could be invalid. But this is not. It is valid to use empty spans I believe. Using validation tool https://validator.w3.org/nu/#textarea with doc example does not throw any warnings or error.
````html
<!DOCTYPE html>
<html lang="" xml:lang="">
<head>
<title>Example</title>
</head>
<body>
<span></span>
</body>
````

However, I understand this is not useful and it comes from Pandoc processing. I'll think about if we should do something on our side, or maybe if Pandoc should not keep `spans` if empty when processing the headers link content for the TOC. Not sure if this is easy or not.

Options for use would be to post process the HTML, or adapt the anchor section features to add the content using JS only and not adding the `<a>` from the Lua filter. But we may loose some feature in this case I think 🤔

**Comment by avraam-inside** [comment]
`anchor_sections: false` helped, thanks!

P.S.: The issue has been edited - removed unnecessary adjectives

**Comment by cderv** [comment]
@avraam-inside this is now fixed in the dev version. 

Thanks a lot for the report as it had the side effect of revealing also some other issues with new Pandoc 2.18.
