### ISSUE TITLE
render_book("filename") complains about missing "index.Rmd"

### ISSUE THREAD

**Issue by otoomet** [rstudio/bookdown#1349]
I have a project in a separate folder that contains three files (and only these three files):

_foo.rmd`_

    # Chapter Foo

_bar.rmd_

    # Chapter bar

and __bookdown.yml_:

    book_filename: foobar
    
    rmd_files: ["foo.rmd", "bar.rmd"]

I attempt to knit the book as

```bash
Rscript -e "bookdown::render_book('foo.rmd')"
```
This gives me an error
```
Error in stop_if_not_exists("index.Rmd") : 
  Some files were not found: index.Rmd
Calls: <Anonymous> -> stop_if_not_exists
Execution halted
```
So bookdown is looking for _index.Rmd_ although this file is nowhere in my project, and `?render_book` states that

> ...
> input: A directory, an input filename or multiple filenames. For a
>     directory, ‘index.Rmd’ will be used if it exists in this
>     (book) project directory. For filenames, if ‘preview = TRUE’,
>     only files specified in this argument are rendered, otherwise
>     all R Markdown files specified by the book are rendered.

This occurs in R 4.2, bookdown 0.27 and also the github version 0.27.1.  It worked in R 4.1, bookdown 0.24.

For a larger project a workaround seems to be to create an empty _index.Rmd_ file, but not for this simple example.

```
> xfun::session_info()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  compiler_4.2.0  graphics_4.2.0  grDevices_4.2.0 parallel_4.2.0  stats_4.2.0     tools_4.2.0     utils_4.2.0     xfun_0.31      
```

**Comment by cderv** [comment]
I had another report of this recently in https://community.rstudio.com/t/render-book-error-stop-if-not-exists-and-some-files-were-not-found/139927/19

I don't think it comes from the same code part, but change impact this is the same. In **bookdown** 0.27 we enforced the checking of `index.Rmd` files that are expected in a **bookdown** project. This is where the YAML header for the book metadata are stored. 

We were not checking for `index.Rmd` before but assume it was there. Some feature were not working well before because of that (auto guessing output format) as we introduced the check to fix https://github.com/rstudio/bookdown/pull/1332 

I think the error is thrown for you from 
https://github.com/rstudio/bookdown/blob/7e9b46fee109f06f86962d6a78b801d3491c94aa/R/render.R#L79-L87 from this part, and is necessary so that we can correctly detect which format to use (merging all format from `_output.yaml` and `index.Rmd`. 

It seems **bookdown** was used without  a `index.Rmd` file without much issue. So maybe we need to reconsider and be less strict about this file existence. 

Where are you format defined if not in a `index.Rmd` file ? Do you have a YAML header in `foo.rmd` or another file ? All our template and example are using a `index.Rmd` which is always the first file of a project. 

@yihui what is you take on this ? 
Was `index.Rmd` always assumed to be in the project ? I thought so bu maybe not. 
Otherwise, we were not aware of usage without this `index.Rmd` file. 

Thanks.

**Comment by otoomet** [comment]
@cderv , was it a question to me?

* I never tried the "foo" example with bookdown 0.24.  So I cannot tell if it works (sorry, overlooked it in the bug report).
* In my actual project, I have _index.rmd_ (not lower case "r"), and so far `Rscript -e "bookdown::render_book('index.rmd')"` worked.  Now I also created an empty _index.Rmd_, and it seems to work.
* I am not 100% what do you mean as "output format", I have _bookdown.yml, that defines some of the ouput format parameters:
```
book_filename: machinelearning-py
output_dir: build
delete_merged_file: true
language:
  ui:
    chapter_name: ["Chapter "]
new_session: yes

rmd_files: ["index.md",
"python.md",
"numpy-pandas.md",
"plotting.md",
...
```
(Note: the files are *.md, not *.rmd, see #1262 for explanations)
* The documentation (cited above) mentions _index.Rmd_ as the default file, but it seems like one can use any other file instead of it.

**Comment by cderv** [comment]
> In my actual project, I have index.rmd (not lower case "r"), and so far Rscript -e "bookdown::render_book('index.rmd')" worked. Now I also created an empty index.Rmd in there, and it seems to work.

So this confirms it works with `index.Rmd` files, and if this file is missing we are throwing an error. This is expected behavior currently as we are using `index.Rmd` to scan YAML header for a possible `output` field. 

Usually in a bookdown project, there is a main file with some YAML header. I was wondering which one you used if not `index.Rmd`

**Comment by otoomet** [comment]
I'd add a third option here: c) use the first file specified in the config file to look for the yaml header, and do not require the _input_ argument at all.

**Comment by otoomet** [comment]
Thanks for being so responsive!

**Comment by grimbough** [comment]
I'd like to add my 2 cents that we've been maintaining the book [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/) for several years now where the front page is generated from `index.rmd` provided to the `input` argument. As far as I'm concerned **bookdown** had been working perfectly in that usecase (if some features are missing I haven't noticed them).

> my reading from the docs is that index.Rmd is just the default starting point for directories, but if one submits another file name then it is not needed. This is how I understood the docs, and up to now it also worked in this way: 

My interpretation of the documentation was the same as @otoomet that `index.Rmd` was the default but replaceable.  I'm certainly surprised at the case sensitivity here - capitalised file extensions feel weird and I normally expect `.R` Vs `.r` etc to be treated the same. Perhaps that distinction can be dropped, even if the general `index` filename requirement stands?

Thanks for maintaining this super useful package.

**Comment by cderv** [comment]
Thanks for your feedback @grimbough ! 

What will do based on all your feedbacks: 

* We will support both extensions, `index.rmd` and `index.Rmd` - reverting to previous behavior and improving feature that was suppose to work only with `index.Rmd`

* We will modify the fix from #1332 introduced to fix #1331 so that `index.Rmd` is not required but correctly used if found, and with a fallback mechanism if not found.

**Comment by cderv** [comment]
@otoomet @grimbough #1351 can be tested to see if this fix things for you. If you want to try it out.

```r
remotes::install_github("rstudio/bookdown#1351")
```

**Comment by otoomet** [comment]
Thanks, now works for me even if I remove the dummy `index.Rmd` (there is `index.rmd`).

I thought that someone simply had overlooked an old hard-coded value, but it seems bookdown is quite a complicated project.

**Comment by cderv** [comment]
Thanks for confirming. And yes **bookdown** is quite a complicated workflow, also it is an now old project and it is always a non-so-easy task to adapt. 

`.Rmd` remains the usual extensions expected by many project, and `index.Rmd` the main file where metadata are in project. Hopefully, the PR will help with likish file. 

Thanks for opening the issue.
