### ISSUE TITLE
"extra_dependencies" isn't used.

### ISSUE THREAD

**Issue by piiskop** [rstudio/bookdown#1350]
The command `extra_dependencies` isn't used. For instance, i have in _\_output.yml_:

```
bookdown::pdf_book:
  extra_dependencies: [
    enumitem: null
  ]
  template: template.tex

```
or

```
bookdown::pdf_book:
  extra_dependencies: [
    "enumitem"
  ]
  template: template.tex

```
and in _CSUniSchoolLabReport.cls_:

`\setlist{partopsep=0pt, topsep=0pt} % Customize spacing around and inside lists
`
.

The latter file is references in _template.tex_:

```
documentclass[
	a4paper, % Paper size, specify a4paper (A4) or letterpaper (US letter)
	12pt, % Default font size, specify 10pt, 11pt or 12pt
	onecolumn,
	twoside
]{CSUniSchoolLabReport}

```
.

Compilation ends with the error message:

> ! Undefined control sequence.
> l.34 \setlist
>              {partopsep=0pt, topsep=0pt} % Customize spacing around and insi... 
> 
> Error: LaTeX failed to compile physics-spring-pendulum.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See physics-spring-pendulum.log for more info.
> Execution halted
> 
> Exited with status 1.
>

**Comment by piiskop** [comment]
> $for(header-includes)$
> $header-includes$
> $endfor$

Where should i put these lines to?

**Comment by piiskop** [comment]
Do you mean that i should add these lines into TEX-file? You can see the full source code including _template.tex_ in [physics-spring-pendulum](https://github.com/piiskop/physics-spring-pendulum) project repository.

**Comment by cderv** [comment]
Your `template.tex` needs to be a pandoc template with some parts required for some feature to work (highlighting, ...). Including content in header is one of them, and `extra_dependencies` in R Markdown is leveraging Pandoc feature. So if you want that to work, you need to use a correct `template. tex` file. 

Here, either you add `\usepackage{enumitem}` in your `template.tex` or you add the piece of code that Pandoc's expect so that you can pass variable in YAML. Looking at Pandoc's own template if the best way for you  to get a sense of what it is. 

Some chapter about Pandoc template: https://bookdown.org/yihui/rmarkdown-cookbook/latex-template.html
And official doc is https://pandoc.org/MANUAL.html#templates

**Comment by piiskop** [comment]
i see that there's a lot of reading for me for this summer. i've pretty much ignored everything regarding Pandoc so far because i've seen that comprehensive manual and nothing simpler about it. If this is the way you suggest for me to go, i'll do it.

**Comment by cderv** [comment]
Have a good read ! 

I'll close this as there is no really issue with **bookdown**. 

Feel free to reach out again here if there is some stuff not clear yet. 

Thanks !

**Comment by piiskop** [comment]
i just gave a try to _default.latex_ and created a new project in RStudio for that. i didn't make any other change besides making it to use the default template and compiling to _bookdown::pdf\_book_ failed with

> ! Undefined control sequence.
> l.246 {\centering \includegraphics
>                                   [width=0.8\linewidth]{02-cross-refs_files/... 

.

**Comment by cderv** [comment]
I think this is because you did not activated `graphics` variable in your project for the Pandoc template to add the required part. 

`\includegraphics` in LaTeX requires the `graphics` package, which Pandoc only adds 
https://github.com/jgm/pandoc/blob/e0dea96d6c1e7d6f19040cafd9ffde432de330d8/data/templates/default.latex#L258-L259

What type of graphics are you adding ? If the figure in the markdown file is inserting using LaTeX directly (which knitr can do), and not markdown syntax `![](image/path)` then Pandoc won't activate the variable. 

In **rmarkdown** we do it by default when the default template is used
https://github.com/rstudio/rmarkdown/blob/7eb75a81c7e8ea124b224842c63c19fcaddb8802/R/pdf_document.R#L148-L49

you just need to add `graphics: true` in your YAML. 

We could maybe try to detect LaTeX figure though 🤔
