### ISSUE TITLE
Table numbering/referencing not working when imported from .rds

### ISSUE THREAD

**Issue by kdschneider** [rstudio/bookdown#1361]
# Problem

When importing a table from an .rds file the caption numbering and referencing breaks, even though the R output is the same.

# Example

**In an analysis script:**
```{r}
table <-
  head(mtcars) |>
  knitr::kable(
    caption = "Test"
  )

readr::write_rds(table, "table.rds")
```

**In the bookdown chapter:**

Take a look at table \\@ref(tab:table)!
````
```{r table}
readr::read_rds("table.rds")
```
````

# Session Info

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4, RStudio 2022.7.0.548

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  base64enc_0.1.3 bookdown_0.27   bslib_0.3.1     digest_0.6.29   evaluate_0.15   fastmap_1.1.0   fs_1.5.2        glue_1.6.2     
  graphics_4.2.1  grDevices_4.2.1 highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3 
  methods_4.2.1   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.3     rmarkdown_2.14  sass_0.4.1      stats_4.2.1     stringi_1.7.6  
  stringr_1.4.0   tinytex_0.40    tools_4.2.1     utils_4.2.1     xfun_0.31       yaml_2.3.5     
```

**Comment by cderv** [comment]
Take this example 

`````markdown
---
output: 
  bookdown::html_document2:
    keep_md: true
---

```{r tab1}
table <-
  head(mtcars) |>
  knitr::kable(
    caption = "Test"
  )
readr::write_rds(table, "table.rds")
```

Let's look at `table`

````markdown
```{r, echo = FALSE}
table
```
````

Take a look at table \@ref(tab:tab2)!

```{r, tab2}
readr::read_rds("table.rds")
```

Take a look at table \@ref(tab:tab1)!
`````

When you generate the table in the first place, caption is processed and the label of the chunk will be used as ID : Markdown caption will be `Table: (\#tab:tab1)Test`. 

By saving to RDS you are also saving the caption with the id already in place. You are saving the result already evaluated and not the table itself. This means **bookdown** will already have placed the id in the caption. 

So when loading the RDS content in another chunk, the id of that chunk does not matter. **bookdown** won't process the code chunk as a table to print, because you already saved the processed version. This means that you can reference the table, but **using the reference id from the chunk where the table was created**. 

So either you that id, or you should save in RDS the table object only, and call `knitr::kable(readr::read_rds("table.rds"), caption = '...'`)` if you want to reuse it. This also makes sense to not thave the same caption on two tables in the same document. 

@yihui I am not sure we could do something here when a chunk reuse an already processed table from **bookdown** where caption is already containing an ID ? should be try to handle this somehow ?

**Comment by yihui** [comment]
@cderv You have explained the problem clearly and provided solid suggestions. I don't have anything to add, and I don't think there is anything we need to do here.

**Comment by cderv** [comment]
@kdschneider I think you will need to adapt your workflow to have the labelling correct:
* Either using the label used during the saving
* or either saving the table data and use `knitr::kable()` to print it. 

We'll probably have nothing else we could really do here. Thanks.
