### ISSUE TITLE
Bookdown does not allow Zotero Connector to get the DOI badge metadata

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [rstudio/bookdown#1373]
1- Here I do not use Bookdown, and Zotero connector gets the DOI perfect:
https://estadistica-analisispolitico.github.io/Sesion1/
Zotero shows this in Chrome and Firefox: 
<img width="40" alt="image" src="https://user-images.githubusercontent.com/7110381/186311883-fa841549-fcff-45d3-bdcd-b34ad621ac60.png">

2- Here I  use Bookdown, and Zotero connector can not get  the DOI at all:
https://estadistica-analisispolitico.github.io/Sesion2/
Zotero shows this in Chrome and Firefox: 
<img width="49" alt="image" src="https://user-images.githubusercontent.com/7110381/186311939-4f7ce85b-5f0e-49fa-8bb2-98d4bb0e470c.png">

Is there a solution?

**Comment by cderv** [comment]
Which **bookdown** format did you use exactly ? 
How the first file was created ? **rmarkdown** but not **bookdown** ? 

I am trying to isolate the issue here. 
 
Also, do you know what zotero connector is expecting ? What is the meaning of the two screenshots you set ? 
Sorry but I am not familiar with Zotero connector. 

Another observation from you two documents about the DOI badge (and I don't know if this is related)
![image](https://user-images.githubusercontent.com/6791940/186924458-f73809bc-6947-497d-b9c8-da4dab7970c4.png)

In the first doc, the HTML code is 
````
<a href="https://doi.org/10.5281/zenodo.7015029"><img... alt="DOI"></a>
````

in the second 
```
<a href="https://zenodo.org/badge/latestdoi/526453788"><img ... alt="DOI"></a>
```

so link is not the same. Could this be a problem to Zotero Connector ? 

Overall, we need to know what Zotero connector expects in the HTML file to get the DOI if we want to improve in **bookdown** or elsewhere. 

thank you

**Comment by MAGALLANESJoseManuel** [comment]
Got it!...solved it.
