### ISSUE TITLE
New PX font in pdf_book throws error in collision with amsthm

### ISSUE THREAD

**Issue by strimmerlab** [rstudio/bookdown#1388]
I would like to use the New PX font (`newpxtext` and `newpxmath`) in a bookdown project (see https://tug.org/FontCatalogue/newpx/).  The New PX font is a Palatino clone with mathematics that can be used with pdflatex and that improves over the earlier related `mathpazo` and `pxfonts` packages.

Here is an example markdown file (`index.Rmd`):
```
---
title: "My Book"
date: "2 October 2022"
documentclass: book
#fontfamily: mathpazo  # works
fontfamily: newpxtext,newpxmath # does not work
#fontfamily: amsthm,newpxtext,newpxmath # works
---


# An example

:::{.example #gradient}
Calculation of the gradient:

$$
\nabla f(x) = ...
$$

:::

````
Compiling this using the command `bookdown::render_book('index.Rmd', output_format="bookdown::pdf_book")` throws the following error:
```
 LaTeX Error: Command \openbox already defined.
               Or name \end... illegal, see p.192 of the manual.
```
The reason for this error is that both the package `amsthm` and `newpxmath`  define `\openbox`.  A solution is to load `amsthm` before the font package.

A workaround is to include `amsthm` as a "font":
```
fontfamily: amsthm,newpxtext,newpxmath
```
However, a proper fix should change the place of inclusion of the `amsthm` package in the Latex template for pdf_book.

Packages needed on Debian for New PX fonts to work in Latex:
```
texlive-plain-generic
texlive-fonts-extra
tex-gyre
```
Output from `xfun::session_info()`

```
xfun::session_info()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

Locale:
  LC_CTYPE=de_DE.utf8       LC_NUMERIC=C             
  LC_TIME=de_DE.utf8        LC_COLLATE=de_DE.utf8    
  LC_MONETARY=de_DE.utf8    LC_MESSAGES=de_DE.utf8   
  LC_PAPER=de_DE.utf8       LC_NAME=C                
  LC_ADDRESS=C              LC_TELEPHONE=C           
  LC_MEASUREMENT=de_DE.utf8 LC_IDENTIFICATION=C      

Package version:
  base64enc_0.1.3 bookdown_0.29   bslib_0.4.0     cachem_1.0.6   
  cli_3.4.1       compiler_4.2.1  digest_0.6.29   evaluate_0.16  
  fastmap_1.1.0   fs_1.5.2        glue_1.6.2      graphics_4.2.1 
  grDevices_4.2.1 highr_0.9       htmltools_0.5.3 jquerylib_0.1.4
  jsonlite_1.8.0  knitr_1.40      magrittr_2.0.3  memoise_2.0.1  
  methods_4.2.1   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.6    
  rmarkdown_2.16  rstudioapi_0.14 sass_0.4.2      stats_4.2.1    
  stringi_1.7.8   stringr_1.4.1   tinytex_0.41    tools_4.2.1    
  utils_4.2.1     xfun_0.33       yaml_2.3.5  
```

**Comment by cderv** [comment]
`amsthm` is used by **bookdown** for the theorem and proofs environment. You can disable this feature by setting the option `bookdown.theorem.preamble` to `FALSE` since version [0.23](https://pkgs.rstudio.com/bookdown/news/index.html#changes-in-bookdown-version-023)

In this case, you would need to define yourself in preamble the theorems and proofs environment from `amsthm` yourself. And obviously load `amsthm` in preamble yourself. 

This may not solve the issue though considering how pandoc works

> However, a proper fix should change the place of inclusion of the amsthm package in the Latex template for pdf_book.

We use Pandoc's template (https://github.com/jgm/pandoc/blob/master/data/templates/default.latex) and this template will always define [`fontfamily`](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex#L85-L86) before loading user [header includes](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex#L346-L348), so I don't see an easy way to make `amsthm` loaded in the right place using YAML variable only 🤔 

I think you need to define a preamble yourself that does the thing in the right order using includes (https://bookdown.org/yihui/rmarkdown-cookbook/latex-preamble.html) 

This would be a Pandoc issue to offer more customisations from YAML to load packages before fonts. 

I wonder if it is not a `newpx` issue, that should be solved the same way as in `newtx` (https://www.ctan.org/pkg/newtx) From their doc (https://texdoc.org/serve/newtxdoc.pdf/0): 
> Version 1.7 has a new option, amsthm, which loads that package in the correct order. Without that option, if
> you wish to use the amsthm package, the load order is
> ```latex
> \usepackage{amsmath}
> \usepackage{amsthm}
> \usepackage{newtxmath} % plus other options
> ```
> but this may now be simplified to
> ```latex
> \usepackage[amsthm]{newtxmath} % or newtx
> ```

This way this would avoid the conflict and requirement of package loading order. 

Anyway, I don't think we can do something specific to this issue from **bookdown**, more than allowing to opt-out the preamble tweak by bookdown itself

**Comment by strimmerlab** [comment]
Many thanks for looking into this.  I agree it seems to be rather an issue with the New PX font packages in collision with `amsthm`.    I also understand why one cannot insert packages before the fonts due the link with pandoc.

One way to fix this without changing boot order would be to undefine `\openbox` before loading `amsthm`, see https://tex.stackexchange.com/questions/386739/clash-between-newtxmath-and-amsthm-packages

```
\usepackage{newpxmath} %  fontfamily

% further down 
\let\openbox\undefined % undefine \openbox before it is defined again in amsthm
\usepackage{amsthm}
```
Perhaps it would makes sense to have this in the bookdown Latex as default?

**Comment by cderv** [comment]
> Perhaps it would makes sense to have this in the bookdown Latex as default?

It seems a bit specific to do this by default in a tool like **bookdown** for dealing with a specific font issue. 

As I mentioned, you should be able to insert the necessary LaTeX in header include. Did you try that already ?

**Comment by strimmerlab** [comment]
I tried the following modied example:
```
---
title: "My Book"
date: "2 October 2022"
documentclass: book
fontfamily: newpxtext,newpxmath
output:
  bookdown::pdf_book:
    includes:
      in_header: mypreamble.tex
---


# An example

:::{.example #gradient}
Calculation of the gradient:

$$
\nabla f(x) = ...
$$

:::

```
As you can see I specified the font, then a latex file to be included `mypreamble.tex` with the following content:
```
\let\openbox\undefined
```
Unfortunately, this file is apparently not included before the `amsthm` package is loaded as I get the same error as before:
```
! LaTeX Error: Command \openbox already defined.
               Or name \end... illegal, see p.192 of the manual.
```

**Comment by strimmerlab** [comment]
As far as I can see it there are really only two ways to fix this:
* load `amsthm` before the font   (this is what I did in my first comment by specifying `amsthm as font)
* undefine \openbox before `amsthm` is loaded.

**Comment by cderv** [comment]
What I meant is overriding Pandoc's own mechanism and do everything in your preamble. That means not provide fonts and deactivate bookdown addition of `amsthm`

````markdown
---
title: "My Book"
date: "2 October 2022"
documentclass: book
output:
  bookdown::pdf_document2:
    keep_tex: true
    includes:
      in_header: mypreamble.tex
---


```{r, include = FALSE}
options(bookdown.theorem.enabled = FALSE)
```


# An example

:::{.example #gradient}
Calculation of the gradient:

$$
\nabla f(x) = ...
$$

:::
````

With `mypreamble.tex` being
```tex
\usepackage{amsthm}
\usepackage[]{newpxtext,newpxmath}
```

**Comment by strimmerlab** [comment]
Yes, that works! 👍   Thanks for your help!
