### ISSUE TITLE
word_document2: reference_docx with undefined "Bibliography" style appends an "X" to each citation when it has a URL

### ISSUE THREAD

**Issue by naikymen** [rstudio/bookdown#1394]
Issue:

![image](https://user-images.githubusercontent.com/3259326/205370595-86d63fdf-cb5a-4097-a434-811cd1d885b5.png)

Removing all URLs, DOIs, PMIDs, PMCIDs, etc. will prevent the problem.

![image](https://user-images.githubusercontent.com/3259326/205371381-4f8f19e0-2c71-4458-a33b-16d9e7737fb9.png)

Removing `reference_docx` from the header also fixes the problem.

Adding a "Bibliography" style to the template DOCX will also fix the problem with no trade-offs:

![image](https://user-images.githubusercontent.com/3259326/205371784-2bf111a9-e9ef-4f24-900b-7f6db40451c5.png)

![image](https://user-images.githubusercontent.com/3259326/205372912-127b1e28-6b72-421d-8739-235125859030.png)

I have no idea where to report this, and hope this is the right place :)

Thank you for this awesome software!

**Comment by naikymen** [comment]
reprex (hopefully): [reprex.zip](https://github.com/rstudio/bookdown/files/10143848/reprex.zip)

**Comment by cderv** [comment]
As we document on https://bookdown.org/yihui/rmarkdown-cookbook/word-template.html, using a `reference_docx` supposes that the template file is generated from one created with Pandoc. 
> <sup>From the book: </sup>
>You can apply the styles defined in a Word template document to new Word documents generated from R Markdown. Such a template document is also called a “style reference document.” The key is that you have to create this template document from Pandoc first, and change the style definitions in it later. 

A template file created with Pandoc is expected to have a Bibliography style, and I think Pandoc itself expect to have this style available. 

this happen also with `word_document()` right ? 
Was your reference doc generated from Pandoc or created from scratch without the Bibliography style ? 
I am trying to be sure why this style isn't there and understand correctly. Because in the case of a reference doc created  from scratch, then probably other styling issue could happen. 

> I have no idea where to report this, and hope this is the right place :)

I don't know if we can consider this an issue really, at least if something can be done to improve this (remove the X), this would need to be reported in Pandoc directly. 

A reprex using pandoc only, without **bookdown** or **rmarkdown** layer, would need to share on the repo.

**Comment by naikymen** [comment]
Hello Christophe,

> The key is that you have to create this template document from Pandoc first, and change the style definitions in it later.

I missed that line completely, sorry. How can I generate a DOCX document from pandoc? Would using the output from bookdown work?

My (non-pandoc) reference document was provided by a journal. I was hoping to directly use as it as a reference docx for bookdown. It mostly worked though.

I'm using LibreOffice Writer to edit the DOCX styles, which may be causing issues. Can LibreOffice Writer be used to edit the styles from a pandoc document?

> I don't know if we can consider this an issue really,

We can close this.

> at least if something can be done to improve this (remove the X), this would need to be reported in Pandoc directly.
> 
> A reprex using pandoc only, without bookdown or rmarkdown layer, would need to share on the repo.

I'll try to find the command and post over there.

Thank you!

**Comment by cderv** [comment]
> Would using the output from bookdown work?

Yes using an output generated without reference doc would work. Definitely ! 

> My (non-pandoc) reference document was provided by a journal. I was hoping to directly use as it as a reference docx for bookdown. It mostly worked though

I see. Pandoc team does not provide the requirements of styles that should be present. Maybe there is a way to import in  a docx, all the style for another ? 

What I know is that Pandoc expects name of style to be the same as in reference, and all expected style to be there. Otherwise, some features won't work ok. (mainly styling issue as you've seen)

> I'm using LibreOffice Writer to edit the DOCX styles, which may be causing issues. Can LibreOffice Writer be used to edit the styles from a pandoc document for bookdown?

Isn't Libre Office ODT document ? There is a `bookdown::odt_document2()` which has a `reference_odt` mechanism. It is a different format in Pandoc. 
I don't know if modifying a docx with Libre Office can break the internal structure that Pandoc expects... 🤔 

> I'll try to find the command and post over there.

You can use a markdown document, `.md`, and pass same yaml except `output` part. Then you need to use command line with some flags to generate the document, something like `pandoc --from markdown --to docx --citeproc -o mydoc.docx mydoc.md`

**Comment by naikymen** [comment]
> Isn't Libre Office ODT document ? There is a bookdown::odt_document2() which has a reference_odt mechanism.

Wonderful! Is there a reason why `odt_document2` is not in [the book](https://bookdown.org/yihui/bookdown/#)?

Using the `reference_odt` mechanism resulted in a corrupt ODT (which could not be opened by LibreOffice). I got it to work by skipping it and then [importing the styles manually](https://help.libreoffice.org/latest/ro/text/swriter/guide/load_styles.html) in LibreOffice from the same reference ODT.

I didn't get syntax highlighting with `odt_document2`, so I repeated the steps above with `word_document2` instead.

I wouldn't worry about the corruption issue, it is probably due to the publishers reference DOCX and/or how LibreOffice manages styles during file conversion.

Next time I'll work with a proper reference document with pandoc.

Thanks again :)

**Comment by cderv** [comment]
> Wonderful! Is there a reason why odt_document2 is not in [the book](https://bookdown.org/yihui/bookdown/#)?

No - we probably did not update after adding the function. Thanks for notifying ! 

> I wouldn't worry about the corruption issue, it is probably due to the publishers reference DOCX and/or how LibreOffice manages styles during file conversion.

Just to be clear, you mean there is no specific issue for us to look at with ODT right ? 
It is just happening with your specific publisher DOCX ?

**Comment by naikymen** [comment]
> Just to be clear, you mean there is no specific issue for us to look at with ODT right ?

Yes, sorry for the confusion!

_Maybe_ except for this:

> I didn't get syntax highlighting with odt_document2,

I'll make another issue for it, if it is unexpected.

Otherwise there is nothing to fix :)

Thanks!

**Comment by naikymen** [comment]
Done! https://github.com/rstudio/rmarkdown/issues/2440

I posted on the rmarkdown repo. I realised that the `odt_document` output does not have highlighting either.
