### ISSUE TITLE
Add inter-.rmd hierarchy for nested depth

### ISSUE THREAD

**Issue by leobuchignani** [rstudio/bookdown#205]
Caveats - I'm not an R programmer, and this is just my novice opinion.  This is an enhancement request.

I was excited to adopt Bookdown until I ran into a dealbreaker - lack of inter-file hierarchical nesting.  

Bookdown allows ToC hierarchical nesting, but in the file system all .rmd files are equals.  Hierarchy is expressed intra-.rmd.  

This places a practical ceiling on depth of nesting and total length of the book.  Past a certain length, outline folding and navigation within a single .rmd file become unwieldy.  

Here is my design suggestion: 

1.  Make the default directory for .rmd or .md files a directory like /markdown instead of the root.  This improves ergonomics.

2.  Permit subfolder nesting.  Subfolders denote nesting hierarchy.  Each subfolder may have its own index.rmd file.  If it does not have one, then the heading is simply a placeholder which prints an index of the subfolder's contents.

Benefits: 

This allows a much more fluid book-writing workflow.  The author can start with a single .rmd.  When it gets long, he splits it in two.  Ibid... When he has 15 .rmd's, he begins nesting them into subfolders.  Throughout all these many structural edits, he doesn't need to touch any config files.  He can just alter the numerical prefixes of the files and folders to change their order in the ToC. 

Thus an author may concentrate on writing and let the content organically dictate the structure of his book.

Now, with leaden heart, I will plod into the cold wilderness of Docbook...

**Comment by augustoamerico** [comment]
For what I understood, you are suggesting an "import" feature right?

If I understood correctly, you can have .rmd files in subfolders and then have a root rmd file(like a `index.rmd`)  with the following:
```
--- 
title: "Codatar: The last code-bender"
author: "augustoamerico"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    includes:
      in_header: mathjax-number.html
documentclass: unlthesis
classoption: graybox,envcountchap,sectrefs
bibliography: bibliography.bib
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Thesis for Msc in Computer Science written in bookdown::gitbook."
biblatex: yes
---
```{r include = FALSE}
library(pander)
source("bookdown_utils.R")
fig_basePath = "Figures/"
```

```{r child="Chapters/01-intro.Rmd"}
```

```{r child="Chapters/02-intro-electric-motors.Rmd"}
```


# (APPENDIX) Appendix {-} 

# `r if (knitr:::is_html_output()) ': '`From eletrical charges to Induction Motors for dummies: A Computer Scientist approach

Bla be sahf oashaoas asa nsa bjs gajsi sa ash 

`r if (knitr:::is_html_output()) '# References {-}'`
```

**Comment by leobuchignani** [comment]
I wouldn't consider it importing, any more than .rmd files currently stored in the root directory are "imported".  

Mkdocs has the feature I'm talking about
> Source files inside nested directories will cause pages to be generated with nested URLs
http://www.mkdocs.org/user-guide/writing-your-docs/

**Comment by yihui** [comment]
You are free to put Rmd files in subdirectories -- you just need to specify the filenames in `rmd_files` in `_bookdown.yml`: https://bookdown.org/yihui/bookdown/usage.html because bookdown does not search recursively for Rmd files under the current working directory.

```yaml
rmd_files:
  - "chap1/sec1.Rmd"
  - "chap1/sec2.Rmd"
  - "chap2/sec1.Rmd"
```

Perhaps I should provide an option to allow recursive searching.

RE: `/rmarkdown` vs root, I do not see why this is important. You can change the working directory to `/rmarkdown`, render the book, and switch the working directory back. Or simply `bookdown::serve_book('rmarkdown', daemon = TRUE)` and done. https://bookdown.org/yihui/bookdown/serve-the-book.html https://bookdown.org/yihui/bookdown/rstudio-ide.html

**Comment by leobuchignani** [comment]
> you just need to specify the filenames

That is the problem.  In a realistic workflow, an author may split a document, shuffle files around extensively, and continually check the preview as he does so, to decide whether he likes the result.  Manually reflecting those changes in a config file is so onerous it breaks the workflow.  The worry that one will simply forget or lose a file has a chilling effect on refactoring.

> Perhaps I should provide an option to allow recursive searching.

That would help.  Rippledoc is an example of a static site generator that allows nesting to unlimited depth without touching config files.

> You can change the working directory to /rmarkdown

Ok.

**Comment by yihui** [comment]
In `_bookdown.yml`:

```yaml
rmd_subdir: yes
```

and bookdown will search for Rmd's recursively.

**Comment by stats-ai** [comment]
Hello,  how do I create a "nested" book.  For example, I have a folder, with index.rmd.  What do I do next?  

Currently within the navigation of the book, I can only go 3 levels deep.   I need to be able to go at least 8 levels deep and so I was thinking of creating a book within a book.   If there are other ways to solve this issue, please let me know!

**Comment by cderv** [comment]
Hi @stats-ai, Please if you have a question more than an issue, consider asking on RStudio Community or Stackoverflow. Github issues are more for Issues and Feature request. 

Anyhow, it would also be easier if you open a new issue in GH rather than commenting on an old issue. The feature discussed here has already been implementing with `rmd_subdir` configuration. See the documentation: https://bookdown.org/yihui/bookdown/configuration.html

> Currently within the navigation of the book, I can only go 3 levels deep. I need to be able to go at least 8 levels deep and so I was thinking of creating a book within a book. 

I think you are talking of something different that this issue and it is necessary to open a new question for your specific use case. I also watch the community so I'll be able to provide help there, but also with the help of a broad community ! See you there! 
https://community.rstudio.com/c/R-Markdown/10
