### ISSUE TITLE
Theorem environments do not appear when echo = FALSE

### ISSUE THREAD

**Issue by Selbosh** [rstudio/bookdown#257]
It took me a little while to figure this out, but it appears that environments such as theorems, proofs and so on are silently hidden if the default chunk option is `echo = FALSE`.

That is to say, if we have
```r
knitr::opts_chunk$set(echo = FALSE)
```
somewhere at the start of the document, then an environment
``````
```{theorem}
To be, or not to be, that is the question
```
``````
will not appear in the output. The solution in this case is to put
``````
```{theorem, echo = TRUE}
Is it nobler in the mind to suffer the slings and arrows of outrageous fortune... (etc)
```
``````
and then the theorem will appear.

I'm not suggesting this is necessarily a *bug*, but it should probably be documented, as this behaviour isn't obvious. Just in case anybody else runs into the same problem.

**Comment by rtaph** [comment]
Hi Selbosh. Yihui acknowledged as much in #220. I also had to figure this one out.

**Comment by Selbosh** [comment]
Thanks. I should have seen that one.

**Comment by yihui** [comment]
Hmm, perhaps it is just a bad idea for me to use `echo=FALSE` to hide thereoms. The documentation is kind of hidden here: https://bookdown.org/yihui/bookdown/custom-blocks.html Thanks @rtaph!

**Comment by rtaph** [comment]
Thanks @yihui,

I support rethinking this in a future release. I my own applications, I don't see the choice to show/hide theorems vs. code as one and the same, but using `knitr::opts_chunk` forces that paradigm. I imagine a good many people are going to be using bookdown to write professional-looking publications where they do not want to show code but do want to show theorems, and would want to rely on a global option.

Whether or not this is changed, perhaps including `echo=TRUE` in the example from the Theorems chapter would help? It's easy to miss the documentation since it appears in a later chapter, and people may copy-paste the theorem code into their own scripts when they already have `opts_chunk` set. While redundant in some cases, placing `echo=TRUE` in the example would draw this to the attention of users new to Theorems.

**Comment by yihui** [comment]
That is a very good suggestion! I'll add `echo=TRUE` to the examples. Thanks!
