### ISSUE TITLE
Feature Request: every .Rmd included as \input in the main .tex file

### ISSUE THREAD

**Issue by danbricedatascience** [rstudio/bookdown#259]
This is a feature request.

Today it seems the whole document is in a single .tex file.

It could be nice and cleaner to enable getting one .tex file per .Rmd, and getting each of these files declared as `\input{my-chapter1.tex}` in the main .tex.

**Comment by yihui** [comment]
To exaggerate a bit, bookdown's goal is to hide LaTeX as much as possible -- you read the simple R Markdown in the source, and the beautiful PDF/HTML in the output; anything in-between should not require the author's attention, since the author's main job is to get the book done instead of worrying about how/where .tex files were generated :)

If we have failed to reach this goal and you have to worry about LaTeX all the time for legitimate reasons, we can try harder, but if you just want to split the big .tex per .Rmd, I think it will be a fairly low-priority task for us. Sorry.

**Comment by danbricedatascience** [comment]
Ok Understand. 

My concern was not about being concerned with LaTeX but about optimizing the chapter generation on long documents having heavy computing but avoiding using "Cache" in the chuncks. 

In this perspective it could be very interesting to be able to compile a single .Rmd, so generating a single .tex for the chapter, then pdflatex only has to compile the whole document, the other chapters don't have to be generated again. 

Best Regards

**Comment by yihui** [comment]
There is a preview mode that only renders a single chapter in bookdown (`?bookdown::preview_chapter`), and this is the default behavior when you click the Knit button in RStudio.

That said, here are my humble personal tips: https://bookdown.org/yihui/bookdown/some-tips.html
