### ISSUE TITLE
tufte html book pulldowns do not display on narrow devices like phones

### ISSUE THREAD

**Issue by ajdamico** [rstudio/bookdown#263]
![screenshot_20161210-013134](https://cloud.githubusercontent.com/assets/216807/21070119/a6e2a78c-be78-11e6-8102-12ff53bb1493.png)

thanks for the great software

**Comment by yihui** [comment]
Looks like the z-index of sub-menus is not large enough. I spent the vast majority of time on the gitbook format, and did not really do much work on the tufte HTML book.

**Comment by znmeb** [comment]
I tried the Bootstrap version and it's like this too ... interesting that the RMarkdown site, which is also done with Bootstrap, works fine on a mobile. 
![screen shot 2016-12-09 at 21 02 34](https://cloud.githubusercontent.com/assets/4938/21071364/dc425f6a-be52-11e6-966b-4cdad6010423.png)

**Comment by yihui** [comment]
The problem is that the Table of Contents generated by bookdown does not use Bootstrap. I provided an example CSS file https://github.com/rstudio/bookdown-demo/blob/master/toc.css after about 10 minutes' research. You will have to look for a responsive CSS style by yourself before I'm able to find some time to work on this. Sorry.

**Comment by znmeb** [comment]
That's OK ... I'm sticking with the GitBook style and using Tufte for the PDF.
