### ISSUE TITLE
multiple output formats without re-knitting

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#288]
I generate a book first using `output_format = "bookdown::gitbook"` and would also like to generate  `output_format = "bookdown::pdf_book"`. Re-knitting isn't really a fast option since I've been getting caching errors and the executions takes a while. 

Is there an easy way to `pandoc` the files coming from the `gitbook` output and create pdf? 

Thanks

**Comment by yihui** [comment]
All Rmd files have to be re-knitted for each output format, because your R code chunks may have output that is dependent on the output format, e.g. HTML widgets, and there will be one set of _cache/_files directories for one output format, so you should not run into caching errors, unless you have manually changed `cache.path` or `fig.path` inside Rmd (which is not recommended).

When I really need multiple output formats, I just use an R script to render them all, e.g. https://github.com/rstudio/bookdown/blob/master/inst/examples/_render.R (I call `Rscript _render.R`; this script is unnecessarily complicated since I need to hack at a few things).

**Comment by topepo** [comment]
I wasn't sure if the process always went to markdown with pandoc doing the work to go between formats. 

Not sure about the cause of the caching errors that I've been experiencing. I'll track them down and figure it out. 

Thanks!
