### ISSUE TITLE
add short / long chapter/section title and/or subheading

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#295]
I kinda like to use wordy chapter and section titles, so I've always liked to use something like

```
\chapter[toc version]{doc version}
```

where there could be a short title for all TOC-ish uses, and a long version.

It'd be nice to have this in the LaTeX output, but also in gitbook output, which doesn't look nice with wordy chapter titles.

@VerenaKasztantowicz might also like this

**Comment by yihui** [comment]
I agree this can be useful, but since Pandoc does not have this feature, I'm afraid it will be unlikely for bookdown to come up with special syntax to support it. Basically, I need to weigh the possible effort on two things: you shorten the chapter titles, vs I provide a new feature. The former might be easier 😉

**Comment by maxheld83** [comment]
yes of course, thanks @yihui as always for your generosity and fantastic work!

**Comment by maxheld83** [comment]
just FYI, I've raised this [over at pandoc](https://github.com/jgm/pandoc/issues/3682) to see whether they might, at some point, support long and short headings.

**Comment by rensa** [comment]
I'm wondering about this too. Is it possible (or could it be possible) to use YAML blocks in the individual chapter files (other than the first)? I'm guessing no: it seems like they each get concatenated early on, and you'd end up with YAML blocks in the middle of the document.

It's a shame, though, because chapter metadata would be a natural solution to something like this.

**Comment by puterleat** [comment]
I'm coming to this late, having just been looking for a solution. From reading these threads I can't work out if @yihui has discounted the idea of using:

```
# long header here {.short-title="short title"}
```
... as suggested in one of the linked pandoc issues.  It would be a nice feature from my point of view, as I'd like to be able to specify a really short 'action-like' menu item, but have a longer and more descriptive title within the text itself.

**Comment by yihui** [comment]
We have to wait for Pandoc to implement it: https://github.com/jgm/pandoc/issues/3682
