### ISSUE TITLE
Collapsible TOC in self-contained html

### ISSUE THREAD

**Issue by mRcSchwering** [rstudio/bookdown#314]
When I am rendering a Rmd file such as this one

```
---
title: "Test"
---

# Chapter I

## Section 1

### Subsection 1.1

## Section 2

### Subsection 2.1

# Chapter II

## Section 1

### Subsection 1.1

## Section 2

### Subsection 2.1
```
 as self_contained html with the command

```
render_book( "", gitbook(split_by = "none", self_contained = TRUE, number_sections = TRUE,
          config = list(sharing = NULL, toc = list(collapse = "section"))) )
```
or
```
render_book( "", gitbook(split_by = "none", self_contained = TRUE, number_sections = TRUE,
          config = list(sharing = NULL, toc = list(collapse = "chapter"))) )
```
the TOC is not really collapsible, it is static. If I click on the sections or chapters, even multiple times, nothing happens. If I do the same with `self_contained = FALSE`  and `split_by = "section"` it works fine.

**Comment by yihui** [comment]
That is probably a bug, but I don't have time to investigate it in the near future. Sorry.

**Comment by boeinguy2** [comment]
I have seen the same problem, when I use Internet Explorer.  The problem goes away when I use Firefox

**Comment by yihui** [comment]
Thanks for the additional info! @boeinguy2

**Comment by boeinguy2** [comment]
In fact the gitbook toolbar and other formatting did not work either until I switched to firefox.

**Comment by yihui** [comment]
Okay, I just tested it in the lovely IE and it turns out that it does not support `window.localStorage` when the HTML file is viewed via the `file://` protocol: http://stackoverflow.com/a/3392301/559676

If you have to use IE, the book has to be viewed via a server, e.g.it could be a local server via `bookdown::serve_book()` https://bookdown.org/yihui/bookdown/serve-the-book.html
