### ISSUE TITLE
How to include figure number in the markdown figure caption?

### ISSUE THREAD

**Issue by janeshdev** [rstudio/bookdown#329]
I am struggling to include the figure number in the image imported in bookdown using the markdown syntax such as following: 

```r
  ![Boundary Conditions](img/boundary-conditions.PNG)
```

I can see the label in the output but how to automatically include Figure number and chapter in the figure caption ? I am using gitbook format.

**Comment by JeffreyRacine** [comment]
You could do the following...

in your r code add ` r foo,fig.cap="Yadda yards."` then reference as follows:

See Figure \@ref(fig:foo)

   ```{r foo,fig.cap="Yadda yards."}
   knitr::include_graphics('img/boundary-conditions.PNG)
   ```

**Comment by janeshdev** [comment]
@JeffreyRacine  Thank you so much. Didn't realize `knitr` would handle that.

**Comment by JeffreyRacine** [comment]
Most welcome…

 

From: 
Janesh Devkota <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Monday, February 6, 2017 at 13:15
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Mention <mention@noreply.github.com>
Subject: Re: [rstudio/bookdown] How to include figure number in the markdown figure caption? (#329)


 

@JeffreyRacine Thank you so much. Didn't realize
knitr would handle that.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
