### ISSUE TITLE
Ability to download raw .Rmd

### ISSUE THREAD

**Issue by coatless** [rstudio/bookdown#330]
I'm wondering how feasible it is to allow for the **Download** menu to offer the direct option of downloading the raw `Rmd` file used to construct the chapter.

e.g.

```
https://raw.githubusercontent.com/<username>/<repo>/master/<file>
```

File: **_output.yml config**

```yml
download: ["pdf", "epub", "html", "raw"]
```
where `raw` could be set in a similar fashion to `edit` flag.

```yml
raw:
   link:  https://raw.githubusercontent.com/<username>/<repo>/master/%s
```

The rationale behind this feature is to address the fact that some students are _not_ GitHub users and, thus, would not be able to directly access the `.Rmd` going through the `edit` menu feature since they would need to login. This feature would avoid the steps of having them 

1. Navigating to the repo
1. Finding the correct chapter rmd file
1. Clicking the `Raw` button 
1. Copy and paste into R and/or file save as...

**Comment by yihui** [comment]
Done. I used `rmd` instead of `raw`. The edit link must be provided for `rmd` to work, e.g.

```
bookdown::gitbook:
  config:
    edit: https://github.com/rstudio/bookdown-demo/edit/master/%s
    downloads: ['pdf', 'rmd']
```

One caveat, though, is that not all Rmd files are self-contained (e.g. they may need external data files). Even if they are able to download the Rmd, they may not be able to really compile it. Personally I don't recommend downloading the individual Rmd files. If they want to download anything, it will be safer to download the whole repo instead and build the whole book. Also note that building a book can be different with building an individual chapter. The former uses `bookdown::render_book()`, and the latter uses `rmarkdown::render()`.
