### ISSUE TITLE
Providing args to block2 chunks

### ISSUE THREAD

**Issue by peircej** [rstudio/bookdown#331]
I'm wondering if it's possible to pass custom arguments to a custom block (I'm using block2). I have a LaTeX custom environment and I'd like to put a title on it in a different font to the body text. I'm thinking of something like the `Theorem` blocks have a 'name' option. If the block had something I could access from within the subsequent LaTeX environment definition it would be awesome.

**Comment by yihui** [comment]
You can use the undocumented chunk option `latex.options`, which is a character string to be written after `\begin{environment}`, e.g. for `type = 'bar', latex.options = '[foo]'`, the environment to be generated is `\begin{bar}[foo]`. If that does not meet your demand, I don't have other solutions. You are always able to define your own knitr engines to do whatever you want, if you are willing to learn how engines work.

That said, many people may think I was kidding: https://bookdown.org/yihui/bookdown/faq.html but I was not. Seriously, I believe reinventing too many LaTeX features in R Markdown is not worth it, and it is very very hard to reinvent them properly so that they also work for non-LaTeX output formats.

**Comment by peircej** [comment]
Ah, great. Yes, I understand that I'm pushing beyond the normal bounds and that creating the full complexity of LaTeX would reduce the point of bookdown existing. But the solution you provide above is _exactly_ what I was looking for. :-)

**Comment by yihui** [comment]
Excellent. Phew! 😌
