### ISSUE TITLE
EPUB output cannot handle references across chapters

### ISSUE THREAD

**Issue by dgrtwo** [rstudio/bookdown#332]
If one tries to have a link from one chapter to another, the links in the resulting epub are broken (they can't be resolved by epub readers like iBooks or by Kindlegen, etc).

### Reproducible example

index.Rmd:

```
--- 
title: "Test Book"
output: bookdown::epub_book
---

# Chapter One

See Chapter \@ref(chapter-two) for more.

# Chapter Two

This is Chapter Two.
```

Built with `bookdown::render_book("index.Rmd")`. Here is the relevant part of the resulting `_main.epub/ch001.xhtml`:

```
<section id="chapter-one" class="level1">
<h1><span class="header-section-number">1</span> Chapter One</h1>
<p>See Chapter <a href="#chapter-two">2</a> for more.</p>
</section>
```

This link is broken; it should be to `ch002.xhtml#chapter-two`, or the epub readers won't know to link across chapters.

Note that (in my understanding) this can't be handled by pandoc options, since the link is already generated in `_main.utf8.md` as `See Chapter <a href="#chapter-two">2</a> for more.`. The links would have to be resolved by bookdown.

**Comment by yihui** [comment]
I feel it will be hard for bookdown to figure out which chapter goes to which .xhtml file after Pandoc converts .md to .epub, so this is unlikely to be fixed...

And personally if I have to choose an e-book format, I'd choose PDF instead of EPUB. PDF is almost uniformly better than EPUB in terms of the typesetting quality, and the main drawback is that you have to decide an appropriate paper size when the reading device is relatively small.
