### ISSUE TITLE
Best practices for multiple columns?

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/bookdown#334]
Folks over at the [Marshall Project](https://www.themarshallproject.org/) published an [excellent analysis](https://www.themarshallproject.org/2016/08/18/crime-in-context ) of US crime data. 

While the content is fascinating, I was also struck by their effective use of layout to present a data-rich argument. For example:

![marshall-proj-ss](https://cloud.githubusercontent.com/assets/8197328/22797547/80a13276-eeb3-11e6-8d94-8e050ba0886f.PNG)

I started looking into multi-column formats for bookdown and found that the situation is a little complicated. It seems like the biggest issue is getting consistency across the different output formats that bookdown allows (e.g., gitbook, pdf, word doc, etc.). But more fundamentally, there doesn't seem to be a clear source of documentation for how users should implement a mutli-column layout in a bookdown document.

Let's say I was interested in publishing a gitbook document, should I use [css method](http://stackoverflow.com/a/31754601/5170276) or the [bootstrap method](http://stackoverflow.com/a/38995154/5170276)? Is there a way to configure the document so that the 2-column format would also work with a pdf output?

**Comment by yihui** [comment]
You are absolutely correct that the challenge is consistency across different formats. It is always easy to get a feature working for a specific format.

For this particular case, it may not be too difficult for LaTeX and HTML output, since there are ways in both formats (use the multicol package for LaTeX, and [CSS for HTML](https://www.w3schools.com/css/css3_multiple_columns.asp)). You need to learn more about the `block2` engine in knitr, and #331 may be helpful, too.
