### ISSUE TITLE
google chrome does not support search button of local gitbook files

### ISSUE THREAD

**Issue by dapengde** [rstudio/bookdown#353]
Search button of gitbook files is very helpful, but it is weird that my chrome seems not to support it in local gitbook files. I mean, if I click the search button on top of a local gitbook webpage, nothing happens, except that a `#` is appends to the address, like:

file:///D:/temp/bookdown-demo-master/_book/index.html#

This problem only occurs on my local files when browsed in chrome. Those published ones, such as https://bookdown.org/yihui/bookdown/, are just fine. Furthermore, if the local files are opened by firefox or even IE,  the search button works just perfectly. 

I tried another computer. Chrome still has this problem. Not a big issue, but I would like to report it for fun.

google chrome version: 56.0.2924.87
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.15.1

loaded via a namespace (and not attached):
 [1] backports_1.0.5 bookdown_0.3    magrittr_1.5    rsconnect_0.7  
 [5] rprojroot_1.2   htmltools_0.3.5 tools_3.2.3     yaml_2.1.14    
 [9] Rcpp_0.12.9     stringi_1.1.2   rmarkdown_1.3   highr_0.6      
[13] stringr_1.2.0   digest_0.6.12   evaluate_0.10 
```

**Comment by yihui** [comment]
It is not specific to Chrome. Searching won't work in any browsers if you try to open the HTML files locally. You have to start a web server to view the HTML pages, and the server can be either remote or local. For the latter, see https://bookdown.org/yihui/bookdown/serve-the-book.html

In case you are curious about the technical reason: the problem is that without a server, it is not possible for JavaScript to read the local JSON database via an Ajax request (for security reasons, JavaScript cannot directly read your local files).

**Comment by dapengde** [comment]
Thank you for the kind explanation. Searching works just fine in Firefox and IE, curiously.

**Comment by nuskcalb** [comment]
In my case, using Firefox 53 in Ubuntu 16.04, searching seems to work as intended, and definitely better than Ctrl+F. For example, using Firefox I can search for words that are in code chunks in sub-sections of the book not reachable by Ctrl+F.
