### ISSUE TITLE
published book not listed on bookdown.org

### ISSUE THREAD

**Issue by dapengde** [rstudio/bookdown#382]
Hi Yihui. Thanks again for your great work. Several days ago I published a book in Chinese on bookdown.org, but I cannot see it in the book list on bookdown.org. The URL of my book is

[https://bookdown.org/baydap/papasdiary/](https://bookdown.org/baydap/papasdiary/)

I see on the [About page](https://bookdown.org/home/about.html)  that a few optional fields must be added in the YAML metadata in the index.Rmd. I have done it as follows:

```
description: "This is a diary of a papa, who is me. I want to write the description in Chinese here, but unfortunately an error occurs in yaml.load() when publishing. So, that is it."
github-repo: "dapengde/papasdiary"
cover-image: "images/cover.jpg"
url: 'https\://bookdown.org/baydap/papasdiary/'
```
Could you have a look and let me know if anything is wrong? Thank you!

**Comment by yihui** [comment]
The list of books is updated manually by me, because I have to check if a book is in a reasonably good shape before I list it on the homepage. There are a lot of books that are really skeletons, and I don't want to list them automatically. I just added your book there.

BTW, perhaps I mentioned it before, but anyway, I have a suggestion that you manually add IDs after your chapter/section titles. This is to make sure you have cleaner URLs for the web pages. For example,

```markdown
# 五岁独自睡 {#sleep-alone}
```

Then the page will be `sleep-alone.html` instead of `e4ba94e5b281e78bace887aae79da1.html`.

**Comment by dapengde** [comment]
Achso! I thought it would had been listed on the webpage automatically. Sorry for the misunderstanding.

Yes, many things in this book have to be improved and corrected. It is just a preliminary version and all I wanted was to briefly see how it looked like after _automatically listed on the webpage_. I will surely do as you suggested.

Thanks a lot.
