### ISSUE TITLE
Cmd + Shift + K loses place in html preview

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#40]
Not exactly sure where this issue belongs but if you have:

```yaml
---
knit: bookdown::preview_chapter
---
```

Then pressing Cmd + Shift + K always takes you to the top of the rendered document. This is obviously frustrating when you're working further down the chapter.

cc @jjallaire @jmcphers

**Comment by jjallaire** [comment]
Here's what I think is going on:

1. RStudio previewer will restore any anchor position (e.g. #foo) and
absent that will restore HTML document scroll position.

2. Neither of these is working for bookdown because (a) The anchor position
isn't updated as you scroll; and (b) Scrolling position is within a div
rather than for the whole document.

I think this could be overcome via one of two measures:

1. Update the anchor position as the user scrolls; or

2. For chapter preview mode use document scrolling rather than div
scrolling.

@yihui Does it sound like I'm on the right track here?

**Comment by yihui** [comment]
What I actually do when I preview the bookdown book is to use the RStudio addin "Preview Book", which calls `bookdown::serve_book()` to serve and preview the book. I have specifically addressed this issue of restoring the scroll position in servr and bookdown. After you call `serve_book()`, the only left for you to do is write and save the Rmd's. There is no need for Cmd + Shift + K.

That does not really address the original issue, though. @jjallaire I believe you are on the right track. That was what I almost tried to do but I implemented the previous approach since it was much easier. I can certainly come back and work on this later on.

**Comment by jjallaire** [comment]
I think it would definitely be nice to have Cmd+Shift+K work well for
chapter level preview as that's such a familiar and convenient gesture (and
also supports side-by-side preview).

**Comment by yihui** [comment]
Yes, I agree. FWIW `serve_book()` actually does chapter-level preview by default.
