### ISSUE TITLE
Navigation buttons missing on the page before appendix

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#407]
e.g. https://bookdown.org/yihui/bookdown/publishers.html Seems to be a bug.

**Comment by dataopt** [comment]
I see all the navigation buttons.
![screen shot 2017-06-14 at 8 46 54 am](https://user-images.githubusercontent.com/28999218/27132773-11e1ed70-50de-11e7-8c34-f6d912ea1e71.png)

**Comment by yihui** [comment]
I mean the left/right buttons, e.g. on this page https://bookdown.org/yihui/bookdown/github.html

**Comment by dataopt** [comment]
It looks like it is caused by an extra `</div>` tag right before `</section>`.

**Comment by yihui** [comment]
Thanks! If you have time to fix it, a pull request will be welcome!

**Comment by dataopt** [comment]
I noticed that for my own book, if I use `split_by = Rmd` under `gitbook`, the last level-2 sections (which are in their own files) always have missing page buttons.  The reason is that the extra `</div>` is supposed to close the `<div>` for the opening of the level 1 header which unfortunately is in a different html file after splitting.   Changing to `split_by = section` makes the problem disappear for reasons unknown to me.

This observation made the Bookdown book one a bit mysterious because it happens to only one chapter but it doesn't happen to the other last level-2 sections.

I need some time to look into this.  In the meantime, could you tell me which R function splits the large html file from pandoc into small html gitbook files?

**Comment by dataopt** [comment]
This is interesting.  It looks like the bug under `split_by = section` happens right before an Appendix section that is unnumbered.  If the Appendix is numbered or if it is a regular section numbered or unnumbered, the buttons are back.  That means there is something wrong with the handling of section divs right before an unnumbered Appendix.

**Comment by dataopt** [comment]
I think I have a fix for the disappearing page navigation buttons.  @yihui: could you create another  branch so that I can make a pull request there for further testing?

**Comment by yihui** [comment]
You don't really need me to create a branch. You can create a branch in your repo and submit the pull request. Thanks!

**Comment by dataopt** [comment]
I know.  But I was hoping to make a pull request not directly to the master branch until more people have tested it.

**Comment by yihui** [comment]
If anyone wants to test your fix, he/she could install the package using `devtools::install_github("rstudio/bookdown#N")` where `N` is the number of the pull request. There is still no need to make a branch.
