### ISSUE TITLE
pdf_book is trying inject latex code to use package amsthm

### ISSUE THREAD

**Issue by therimalaya** [rstudio/bookdown#417]
In your latex.R file, line number 218 is trying to load `amsthm` package. The template I am using is based on a class file which already loads these package. Wouldn't it be nice to include `usepackage{amsthm}` command on your default template instead of injecting it from post processing. The line is,

    x = append(x, c('\\usepackage{amsthm}', theorem_defs, proof_defs), i - 1)

**Comment by yihui** [comment]
The problem is that if I add it in the template, it is not straightforward for users to remove it if they do not really want it (they will have to provide their own template). In your case, you also want to remove it. Currently the only way is to provide your custom post-processor by defining a global option `bookdown.post.latex` as a function. See https://github.com/rstudio/bookdown/releases/tag/v0.4

**Comment by therimalaya** [comment]
For Now, I managed to remove the effect of `render_block2()` function from `pdf_book` adding following chunk to my index.Rmd,


```{r set_option, include=FALSE, echo = FALSE}
options(bookdown.post.latex = function(x) {
    from <- which(grepl("^\\\\usepackage\\{amsthm\\}", x))
    to <- which(grepl("^\\\\theoremstyle\\{remark\\}", x))
    x <- x[-c(from:to)]
  })
```

If you have any better solution, please suggest me.

**Comment by yihui** [comment]
I don't have a better solution than yours.

Just a nitpick: `which(grepl(..., x))` is equivalent to `grep(..., x)`.

**Comment by andry-tino** [comment]
From maintainability perspective, wouldn't it be better to allow `pdf_book` to take in an argument preventing the injection of:

- `amsthm`.
- Any definition of environments as `theorem`, `corollary`, etc.

The solution with `options` is very _global_. This fix would allow a more scoped directive.
