### ISSUE TITLE
Suggestion for additional theorem environments

### ISSUE THREAD

**Issue by dshuman1** [rstudio/bookdown#422]
It would be really nice to have the following additional theorem environments in the bookdown package:

- Exercise (behaving like Definition) (or Question if Exercise will cause too much confusion with Example)

- Solution (behaving like Proof)

**Comment by dshuman1** [comment]
I tried to implement this and made a corresponding pull request.

**Comment by bob-carpenter** [comment]
+1.  I would very much like to see Exercise and Solution.  I like to have my exercises interspersed in with the text and I like to include references to specific exercises (typically ones that fill in useful details).  Right now, I'm instead following the Grolemund and Wickham *R for Data Science* approach of just putting them in their own section at the end.

Would there be a way to make a generic environment so that I could introduce my own such environments?  This feature is supported by LaTeX?  I'm afraid I don't really know enough R to help build this.

**Comment by dataopt** [comment]
Another useful environment is Algorithm.

**Comment by yihui** [comment]
@dshuman1 Your PR has been merged. Sorry for the delay.

@bob-carpenter Yes, it will be helpful if users can define arbitrary custom environments, but I don't have a good mechanism in bookdown to do that right now. Please feel free to request more environments if you need them.

@dataopt [Algorithms](https://en.wikibooks.org/wiki/LaTeX/Algorithms) are different with theorems in LaTeX, so they cannot be implemented as easily as theorems. The major challenge is that it is difficult to provide a portable environment that works for all output formats: it is super easy if you only need to consider LaTeX output. You can just use raw LaTeX: https://bookdown.org/yihui/bookdown/faq.html I don't know what to do when the output is HTML or EPUB.

**Comment by bob-carpenter** [comment]
Specifically, I'd like to use `exercise`.  I had just thought it might be easier to solve the problem in general than keep adding cases, but `exercise` is all that I really need.

**Comment by yihui** [comment]
@bob-carpenter Great! Again, feel free to let me know if you need other types of environments in the future.
