### ISSUE TITLE
[FR] Paragraphs numbering

### ISSUE THREAD

**Issue by alexandre-mbm** [rstudio/bookdown#453]
With cross-referencing (see issue #74).

**Comment by yihui** [comment]
Page numbers are only meaningful for output formats that actually have pages. For example, there is no such concept of pages in HTML output, so I guess this feature won't be implemented.

Also see the FAQ if you only care about LaTeX/PDF output: https://bookdown.org/yihui/bookdown/faq.html

**Comment by alexandre-mbm** [comment]
Paragraphs, nota pages. They could be to rendered on HTML.

**Comment by yihui** [comment]
Oh I see. But (1) it seems to be difficult to implement (I have to completely invent it by myself); (2) I don't know how to make it work for LaTeX output; (3) I don't know how it is supposed to work for paragraphs on a different page.

Personally I'm not in favor of too many cross-references in a book: https://github.com/rstudio/bookdown/issues/238#issuecomment-259059755. I tend to believe that it is better to structure the book/document more clearly so that readers don't have to jump back and forth while reading the book.

So thanks for the suggestion, but I don't think this is going to be implemented anytime soon or at all...
