### ISSUE TITLE
`render_book()` should not delete custom config files

### ISSUE THREAD

**Issue by clauswilke** [rstudio/bookdown#509]
I just tried the new custom config option, and I noticed that `render_book()` temporarily deletes my custom config file and also overwrites my default `_bookdown.yml` file. If all goes well, things are restored properly at the end of the compile, but if anything goes wrong (R crashes, pandoc crashes, power goes out, whatever) then this can lead to data loss. Also, if I have either my custom config file or my `_bookdown.yml` open in RStudio then RStudio will detect the changes and inform me the file has been deleted or reload the file, respectively.

This issue is conceptually related to #405. The bookdown package should not touch any source files whatsoever.

The correct way to handle all these issues, I think, would be to copy all the source files into a temporary directory and do the compile there.

**Comment by yihui** [comment]
It is not deleted but temporarily renamed, so it won't be permanently lost even if very bad things happen such as power goes out. On the other hand, if you are worried about losing files, there are many ways to prevent it, such as version control, Dropbox, and so on.

The difficulty in "copying all source files" is that it is hard to know "all". You cannot make the assumption that the book project is self-contained under a certain directory; if a file in another directory is used (e.g., `read.csv('../../foo.csv')`), you will have to copy it and preserve the directory structure. That will open a can of worms.

I just changed the tempfile path to be under the current working directory, so the temporary config file is more visible to you if bad things happen, and you will be able to manually rename it back.

I think this issue is relatively minor, and I don't want to spend a huge amount of time on it. If you are deeply worried about it, I will add a note in the documentation and recommend the only reliable way to solve the problem, which is you manually copy all your source files to a new directory (you are responsible for copying all necessary files), name your config file as `_bookdown.yml`, and render your book there. You can weigh this approach against the current one, and decide which way you want to go.
