### ISSUE TITLE
How to change caption label names in a single document with Bookdown?

### ISSUE THREAD

**Issue by frkbr** [rstudio/bookdown#515]
I have posted [my question on Stackoverflow](https://stackoverflow.com/questions/48247787/how-to-change-caption-label-names-in-a-single-document-with-bookdown) on how to change caption label names in a **single** document into a different language. I can't find the configuration file `bookdown.yml` that is mentioned in [section 4.5 Internationalization](https://bookdown.org/yihui/bookdown/internationalization.html) when creating a single document with Bookdown. Any help would be greatly appreciated.

**Comment by mschilli87** [comment]
@frkbr: I tried to answer your SO question as good as I can.
If you need more help, feel free to comment there.

---
If your problem is solved, don't forget to close this issue. :wink:

---
If you feel the documentation should be improved, I suggest you open a pull-request suggestion the changes you would like to see.
There is no need to know any git-foo for this, as you can simply [edit the Rmarkdown file online](https://github.com/rstudio/bookdown/edit/master/inst/examples/04-customization.Rmd).

**Comment by yihui** [comment]
@mschilli87 That is a 💯 answer! 👍 👍 👍  Much appreciated!

**Comment by frkbr** [comment]
Thanks, that worked!

**Comment by ayopasaa** [comment]
This solution does not work for .doc documents, I cannot find a solution
