### ISSUE TITLE
Using directories like "en" and "es" for multiple language books 

### ISSUE THREAD

**Issue by ghost** [rstudio/bookdown#539]
I would like to be able to have a button on my book that lets users easily toggle the spanish or english versions of it, preferably without making two separate books hosted on Bookdown.org. I'd like if it were similar to how I think the [Open-Review Toolkit](http://www.openreviewtoolkit.org) is doing things (with "es", "en", etc. directories where you can easily store all the versions as rmd files and have them on a /en/ page). I know this is probably already out there somewhere, particularly for blogdown, I'm just having trouble finding it. 

I've searched around and tried asking on Stack Overflow, but was directed to some resources that didn't seem to really provide help with this kind of multi-language publishing.

**Comment by gd6** [comment]
Hi mschilli! Here is a link to one of the closed questions, it isn't the page I saw originally though, will try to find the other one: https://stackoverflow.com/questions/48635096/what-is-a-way-to-publish-bookdown-books-using-en-and-es-directories-for-span

**Comment by cderv** [comment]
Related to https://github.com/rstudio/bookdown/issues/965

**Comment by apreshill** [comment]
Looks like this user no longer exists, but I am curious if the use case for multilingual books is primarily for the HTML output format (i.e., gitbook or bs4_book)? I ask because Hugo has built-in support for multiple languages, and several Hugo themes deliver a book theme. We have gotten this request for distill sites as well: https://github.com/rstudio/distill/issues/261

**Comment by cderv** [comment]
I did not saw this ghost user. Closing in favor of #965
