### ISSUE TITLE
how to set twoside in ./inst/example

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#583]
I see in krantz.cls, there are many options, such as `\DeclareOption{twoside}`， how to pass these options in latex `\documentclass[twoside]{krantz}` to bookdown?

thank you.

**Comment by yihui** [comment]
Set `classoptions: twoside` in YAML. See https://bookdown.org/yihui/bookdown/latexpdf.html and the reference to the Pandoc manual there.

---

Usually I can only handle Github issues for bug reports and feature requests, and I don't have time to answer general questions. Please try to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with minimal, self-contained, and reproducible examples), so that you may quicker responses from other people instead of having to waiting for me to answer your question. If you are not sure if it is a bug report or a question, consider using StackOverflow first (I watch StackOverflow questions closely every day). You may also try the [RStudio Community](https://community.rstudio.com). Thanks!
