### ISSUE TITLE
Is it possible to insert a xaringan slides as a chapter in bookdown?

### ISSUE THREAD

**Issue by badbye** [rstudio/bookdown#625]
Theoretically speaking, it is possible (in the HTML format). Not sure if it is easy to implement.

**Comment by yihui** [comment]
In theory, yes, you can render remark.js slides on any HTML page. The problem is that slides will always be fullscreen (at least by default), so you won't be able to see other content on the page.

I'd recommend using iframes in this case. You can use the function `knitr::include_url()`: https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html
