### ISSUE TITLE
About Biber in bookdown

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#651]
I find that bookdown has the same problems in https://github.com/sjtug/SJTUThesis/issues/378 

Can we set `biber --decodecharsset=null` in `_out.yaml` file? Thank you.

**Comment by cderv** [comment]
I think this indeed need support in **tinytex** so that it works in **bookdown**. 
I'll close in favor of **tinytex** issue. 

As a workaround, you may need to build by using the non emulation mode of **tinytex**
```r
options(tinytex.latexmk.emulation = FALSE)
```
This will use directly the `latexmk` program. **Obviously this is for advanced use only** and you need to understand what you doing. See https://rdrr.io/cran/tinytex/man/latexmk.html for doc about the `emulation` argument.

From there, it seems you can pass argument to bib engine for `latexmk` using this trick: https://tex.stackexchange.com/questions/331504/passing-options-to-biber-through-latexmk

Anyway, this should be supported in **tinytex**. We welcome a PR in **tinytex** for this.

Thanks!
