### ISSUE TITLE
Cover page and the logo can't be added and download of EPUB and Mobi failed

### ISSUE THREAD

**Issue by Frank-Sw** [rstudio/bookdown#654]
When I compile the Master file example 'index.rmd' the cover page and logo failed to be added. 
There is a warning message: 
The label(s) fig:does-not-exist not found

Besides, EPUB and MOBI in the download logo, can't be done said no such files.

Best,
Frank

**Comment by cderv** [comment]
Thank you for your patience. 

If you want to start with **bookdown** I suggest you use the template: https://github.com/rstudio/bookdown-demo

Build the bookdown book is not always easy and you don't know all the specificity. Fro example the warning is expected because the book explain unused reference. 

Please if you still have issue, open a new one with a detailled reproducible example or steps. Thank you!
