### ISSUE TITLE
LaTeX References treated as subsection of Appendix

### ISSUE THREAD

**Issue by ntrlshrp** [rstudio/bookdown#680]
On page 116 (https://bookdown.org/yihui/bookdown/bookdown.pdf), the header says, `C Bibliography` as if "When the output format is LaTeX, citations will be automatically put in a chapter or section."[1] that is a new **subsection** of section C of the Appendix. Substituting `# References {-}` does the same. 

Substituting `# References` transforms References into **section** D of the Appendix.

This seems to me a bug and makes my bibliography look like it contains a mistake in the header.

Expected behavior is that the Appendix ends and a new "chapter" or "section" begins and headers on right-hand pages say "References" and headers on left-hand pages are either blank or say "References" or something better. Thanks.

[1] https://bookdown.org/yihui/bookdown/citations.html

**Comment by yihui** [comment]
![image](https://user-images.githubusercontent.com/163582/57541088-dd8ba480-7313-11e9-99bc-dea3dd55ec38.png)

I feel that is a bug of the LaTeX class `krantz.cls` at https://github.com/rstudio/bookdown/tree/master/inst/examples. I don't have enough LaTeX expertise to figure out a fix. Perhaps we need to empty the counter in the `thebibliography` environment. I don't know. If anyone knows how to fix it, I'll truly appreciate the help.

**Comment by rstub** [comment]
The way `krantz.cls` treats headings is mixed up indeed. Minimal example:

```latex
\documentclass{krantz}
% \documentclass{book}
\bibliographystyle{unsrt}
\usepackage{blindtext}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\begin{document}
\frontmatter
\tableofcontents

\mainmatter

\chapter{Intro}
\blindtext[10]

\nocite*

\appendix

\chapter{Foo}
\blindtext[10]

% from TeX Live package "beebe"
\bibliography{texnique}

\end{document}
```

Some screen shots:

![image](https://user-images.githubusercontent.com/27821131/62821470-b09a9800-bb75-11e9-8eff-4dbaed91b4e9.png)

![image](https://user-images.githubusercontent.com/27821131/62821473-c314d180-bb75-11e9-83ef-5a89d9b3796a.png)

![image](https://user-images.githubusercontent.com/27821131/62821477-d1fb8400-bb75-11e9-84e9-d8c9e98d81c7.png)

The last screen shot shows the reported issue. The other two are probably related. All these issues do not occur with `book.cls`

Right now I can offer only a workaround for the reported issue: Place `\backmatter` before `\bibliography` in the TeX file. For the `bookdown` example this means placing it somewhere in `10-references.Rmd` and removing it from `latex/after_body.tex`.

**Comment by rstub** [comment]
Some of the oddities seem to be deliberate:

https://github.com/rstudio/bookdown/blob/ea09a1a98daffeb3074582b47c13607dad229657/inst/examples/krantz.cls#L349-L362

This basically adds the formatted chapter and section number into the running head if one is within  `\mainmatter`. This means that any unnumbered chapter and any chapter without an "early enough" first section would cause such problems. A partial fix would be to check the counter value and only print it if greater than zero:

```diff
 \top@cornermarks
   {\@the@page\RunningHeadFont
     \hfill
-\if@mainmatter\thechapter\enspace\fi\leftmark
+\if@mainmatter\ifnum\value{chapter}>0\thechapter\enspace\fi\fi\leftmark
     }}
 \def\odd@head{%
 \top@cornermarks
   \hfil{\RunningHeadFont
-\if@mainmatter\thesection\enspace\else\fi\rightmark
+\if@mainmatter\ifnum\value{section}>0\thesection\enspace\fi\fi\rightmark
     }
 \hfill
     \@the@page \top@cornermarks
   {\@the@page\RunningHeadFont
     \hfill
-\if@mainmatter\thechapter\enspace\fi\leftmark
+\if@mainmatter\ifnum\value{chapter}>0\thechapter\enspace\fi\fi\leftmark
     }}
 \def\odd@head{%
 \top@cornermarks
   \hfil{\RunningHeadFont
-\if@mainmatter\thesection\enspace\else\fi\rightmark
+\if@mainmatter\ifnum\value{section}>0\thesection\enspace\fi\fi\rightmark
     }
 \hfill
     \@the@page
```

The issue with zero section number would be resolved by this (first two screen shots). This does not reported issue, though. I see several approaches there:

1. Embrace the workaround suggested above as the way `krantz.cls` is meant to be used.
2. Set the chapter counter to zero at the start of the bibliography.
3. Save the chapter counter and set it to zero at the begin of the bibliography. Restore the chapter counter after the bibliography.

My preference would be 1., since that seems to be the way the class is intended to be used, though I am not sure it is documented. With 2. one would get strange chapter numbers if one adds a numbered chapter after the bibliography. With 3. this would be fixed, but the TOC is mixed up in both cases: The bibliography is added to it instead of the chapter.

Any preferences? I can provide a PR for any of the above.

**Comment by yihui** [comment]
@rstub I trust your LaTeX skills more than my own, so I'll merge your PR of any of your choice. Thank you!

**Comment by yihui** [comment]
@ntrlshrp Please see @rstub's fix at https://github.com/rstudio/bookdown/compare/ea09a...a3c02. Or use the new `krantz.cls` under https://github.com/rstudio/bookdown/tree/master/inst/examples. Thanks for the report!
