### ISSUE TITLE
inconsistency of first names in references

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#703]
I noticed that first names in references are treated differently between output formats. For example, in the `bookdown-demo` repo, HTML renders

> Xie, **Yihui**. 2015. Dynamic Documents with R and Knitr. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. http://yihui.name/knitr/.

and PDF renders:

> Xie, **Y**. (2015). Dynamic Documents with R and knitr. Chapman and Hall/CRC, Boca Raton, Florida, 2nd edition. ISBN 978-1498716963.

I prefer the latter. Short of modifying all of the entries in my `bib` file, is there a way to get consistency (or at least force abbreviation)?

**Comment by yihui** [comment]
I have noticed this long time ago, but didn't have a chance to investigate it. I bet we will need a certain `csl` but I just don't know which one to use: https://pandoc.org/MANUAL.html#citations

Anyway, this inconsistency doesn't really bother me since it is pretty much a cosmetic issue. If anyone can figure out the `csl` option, I'd love to use it, otherwise I'm afraid I won't have time for this task.

BTW, it can be worse in the case of multiple authors, e.g. https://bookdown.org/yihui/bookdown/references.html

```
Allaire, JJ, Yihui Xie, Jonathan McPherson, Javier Luraschi, ...
```

The first author is displayed in the format `Lastname, Firstname`, but the rest of authors are displayed in `Firstname Lastname`.
