### ISSUE TITLE
Graphs from inline code not appearing when Github Hosts

### ISSUE THREAD

**Issue by Falnesio** [rstudio/bookdown#707]
I have no idea why the inline code graphs do not appear in [my annotations book](https://falnesio.github.io/Datacamp/introduction-to-the-tidyverse.html#grafico-de-vela). I think this may be the best place to find an answer. I am having a hard time interpreting the documentation, I am fairly new to coding(so much so that I coudn't understand how to add a simple edit on github button).

[repo](https://github.com/Falnesio/Datacamp)

**Comment by YunranChen** [comment]
Same problem here. Can see the plots in the local files. Not sure what happens.

**Comment by yihui** [comment]
Please see the last sentence of the first paragraph at https://bookdown.org/yihui/bookdown/github.html. The reason why you need `.nojekyll` is because otherwise Github will build your website using Jekyll, and Jekyll will ignore files/folders that start with underscores such as `_main_files`.

@YunranChen's method works because `docs` does not start with an underscore. Any other `book_filename` will work as long as it doesn't start with `_`.

In the future, please follow the issue guide to ask questions on Stack Overflow or RStudio Community first. Thank you!
