### ISSUE TITLE
Bibtex references showing up twice...or not?

### ISSUE THREAD

**Issue by rikcrutzen** [rstudio/bookdown#751]
We (@Matherion and me) use Bibtex for citations in RMarkdown project. A certain reference (Peters, G.-J.Y., and R. Crutzen. 2017. “Pragmatic Nihilism: How a Theory of Nothing Can Help Health Psychology Progress.” Health Psychology Review 11: 103–21.) shows up twice (while only being cited once) in the reference list of the specific chapter (see: https://a-bc.gitlab.io/bbc/selecting-determinants.html). Is this a known bug? Or does somebody know why this happens? What makes it even more striking is that this same reference does _not_ show up twice in the reference list of the overall project (see: https://a-bc.gitlab.io/bbc/references.html). Any thoughts or ideas are welcome. Thank you in advance.

---

By filing an issue to this repo, I promise that

- [X] I have fully read the issue guide at https://yihui.name/issue/.
- [X] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
That sounds like a bug, but I don't have time to investigate it. If anyone is interested in helping out, please look for `split_bib` in https://github.com/rstudio/bookdown/blob/master/R/html.R and check what went wrong (possibly with `parse_references()` or `relocate_references()`). Thanks!

**Comment by Matherion** [comment]
I'll see whether I can figure out what's going wrong!

**Comment by leowill01** [comment]
I figured out what was wrong in my case. I had been using `output: book down::pdf_document2: pandoc_args:` to add additional arguments for including Lua filters (e.g. `"--lua-filter=pandoc/scholarly-metadata.lua"`), but I also had put the `"--citeproc"` option there as well. The problem arises because the default `knit` to `bookdown::pdf_document2` command already includes a `--citeproc` option. So by including this again under `panic_args:`, I was telling it to insert the complete bibliography twice. 

@rikcrutzen : Check to make sure you don't have an extra `output: book down::[format]: pandoc_args: "--citeproc"` enabled in the YAML header of the chapter you're having an issue with.

**Comment by cderv** [comment]
@Matherion sorry for the delay on this. Is this still an issue ? 

I have clone your repo and rebuild the book locally and I can't see the duplicated reference. It is possible this has been fixed since, especially if it was introduced by a Pandoc version. 

If this is still an issue please share your pandoc version. Thanks!
