### ISSUE TITLE
Applying custom style for table caption adds "Table:" to its caption

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#780]
Below  is a small markdown document with captioned table:

```
---
output:
  bookdown::word_document2: default
---

::: {custom-style="Subtitle"}
Table: (\#tab:tab-comp) Comparison rows and cells
:::

| Header 1 | Header 2 |
|----------|----------|
| r 1, c 1 | r 1, c 2 |
| r 2, c 1 | r 2, c 2 |

```

I expect that the table caption would be styled  with *Subtitle* style and will contain the following text "Table 1: Comparison rows and cells".

But it does not work as expected:

![table](https://user-images.githubusercontent.com/309456/65717208-7182c080-e0a9-11e9-961e-32cf67a89c93.png)

and adds extra "Table:" in front of real caption.

The issue exists with latest Pandoc 2.7.3 and 2.3.1 (shipped as /usr/lib/rstudio/bin/pandoc/pandoc ).

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

```
> xfun::session_info('bookdown')
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS, RStudio 1.2.1578

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 bookdown_0.13.2 digest_0.6.21   evaluate_0.14   glue_1.3.1      graphics_3.4.4  grDevices_3.4.4 highr_0.8      
  htmltools_0.3.6 jsonlite_1.6    knitr_1.25      magrittr_1.5    markdown_1.1    methods_3.4.4   mime_0.7        Rcpp_1.0.2     
  rmarkdown_1.15  stats_3.4.4     stringi_1.4.3   stringr_1.4.0   tinytex_0.16    tools_3.4.4     utils_3.4.4     xfun_0.9       
  yaml_2.2.0     
```

**Comment by cderv** [comment]
Hi, 

there is several things going on here. 

First, the `Subtitle` class is correctly apply but the default reference document does not have a style for it. You should create a reference docx with a Subtitle styles. See [how to use a reference doc](https://rmarkdown.rstudio.com/articles_docx.html)

Regarding table caption, there is pandoc feature, then bookdown feature based on it.
Pandoc allows to specify caption for markdown table (see https://pandoc.org/MANUAL.html#tables) by writing a paragraph beginning with `Table:`. This will create a table to the caption

````r
---
output:
  bookdown::word_document2: default
---

Table: Comparison rows and cells

| Header 1 | Header 2 |
|----------|----------|
| r 1, c 1 | r 1, c 2 |
| r 2, c 1 | r 2, c 2 |
````

![image](https://user-images.githubusercontent.com/6791940/65743757-47a3bb00-e0f6-11e9-9e17-1936f77b574c.png)

See that `Table:` was removed by pandoc. 
I think by applying the custom style in your example, pandoc does not treat this as a Table caption. 

However, `bookdown::word_document2` will use this caption feature to allow cross referencing in document. It will **post process** the document to look for caption keywords (like `<caption>`  in html or `Table:` in markdown) to find caption and add the referencing number adding table. That is why 
````r
---
output:
  bookdown::word_document2: default
---

Table: (\#tab:tab-comp) Comparison rows and cells

| Header 1 | Header 2 |
|----------|----------|
| r 1, c 1 | r 1, c 2 |
| r 2, c 1 | r 2, c 2 |
````
will produce
![image](https://user-images.githubusercontent.com/6791940/65743930-e92b0c80-e0f6-11e9-9379-9ad93e6c568e.png)

There is just one `Table` added by bookdown here, because the table caption is transform already by pandoc into a div of class caption, found by bookdown after to change reference number.
The style is the `Table Caption` style added by pandoc.

Here, you can't mixed all this features together. 

I would advice two different things

You can use table caption for markdown table from Pandoc, then bookdown numbering referencing and you will be able customise the style called `Table Caption` in a reference docx as you wish

Or use `kable()` in a chunk as recommend in the [ Rmarkdown definitive guide](https://bookdown.org/yihui/bookdown/tables.html). This will allow to a reference table label you can use elsewhere in a custom style.

Something like
````r
---
output:
  bookdown::word_document2: default
---

```{r table1}
knitr::kable(
  data.frame(
    "Header 1" = c("r 1, c 1", "r 2, c 1"), "Header 2" = c("r 1, c 2", "r 2, c 2")
  ), 
  caption = "Comparison rows and cells"
)
```

::: {custom-style="Subtitle"}
Like in the table \@ref(tab:table1) Comparison rows and cells
:::
````

![image](https://user-images.githubusercontent.com/6791940/65744952-6441f200-e0fa-11e9-9da5-f39b9da8f803.png)

Hope it helps.

**Comment by N0rbert** [comment]
@cderv Thank you for your nice and comprehensive solution.
I'm already using reference docx. 
So I have changed properties of `Table Caption` style to suite my needs.

The issue here is that I can't use `{custom-style="..."}` for table caption. 
But I know that the same is working normally with figures - see code below:

```
::: {custom-style="figure caption"}
![(\#fig:md) Markdown logo](https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg)
:::
```

and rendering:

![md-fig](https://user-images.githubusercontent.com/309456/65834694-53ee6a80-e2e6-11e9-8f25-291a46e1b129.png)

Should I report table-related problem to pandoc's issue tracker?

**Comment by cderv** [comment]
Hi, 

Thanks a lot for your patience with this. 

I believe this is currently a Pandoc limitation as explained above. Maybe it should be asked about in https://groups.google.com/g/pandoc-discuss

Pandoc examples: 
```powershell
$ pandoc -t docx -o test.docx
::: {custom-style="Subtitle"}
Table: Comparison rows and cells
:::

| Header 1 | Header 2 |
|----------|----------|
| r 1, c 1 | r 1, c 2 |
| r 2, c 1 | r 2, c 2 |
^Z
```
Gives: 
![image](https://user-images.githubusercontent.com/6791940/112360723-e650ae00-8cd2-11eb-86a6-569445355d52.png)

So it is not seen a Table caption by Pandoc. 

```powershell
pandoc -t docx -o test.docx
Table: Comparison rows and cells

| Header 1 | Header 2 |
|----------|----------|
| r 1, c 1 | r 1, c 2 |
| r 2, c 1 | r 2, c 2 |
^Z
```

![image](https://user-images.githubusercontent.com/6791940/112360869-126c2f00-8cd3-11eb-8086-e83609a08f11.png)

Pandoc sees the Table caption and strips the `Table:` part.

Pandoc supports for table caption is described here: 
https://pandoc.org/MANUAL.html#extension-table_captions
and it seems it is not compatible with [custom styles ](https://pandoc.org/MANUAL.html#custom-styles)

I am not sure there is something to do in **bookdown** for this specific Pandoc feature unfortunately. I believe workarounds from https://github.com/rstudio/bookdown/issues/780#issuecomment-535795595 still stands.

**Comment by N0rbert** [comment]
Thanks, but for me this bug still exists with latest Pandoc 2.18 and bookdown from github. Is it really closed as fixed?

**Comment by yihui** [comment]
> So I have changed properties of `Table Caption` style to suite my needs.
> 
> The issue here is that I can't use `{custom-style="..."}` for table caption.

I'm afraid there isn't much that we could do on **bookdown**'s side (I'm also skeptical that Pandoc will ever support table captions wrapped in fenced Divs). Your only option for now is to use the `Table Caption` style. If that won't satisfy your need, I don't know what we could do (not sure if Lua filters could help). Sorry.
