### ISSUE TITLE
unknown cross-reference number with gitbook

### ISSUE THREAD

**Issue by ThierryO** [rstudio/bookdown#787]
The gitbook version displays `??` instead of the correct number when cross-referencing headings that are followed by a higher level heading instead of a paragraph. This occurs in the example below with Part I (always) and Chapter 2 (with `split_by: "section+number"` not with `split_by: "chapter+number"`)

The pdf output works as expected.

## MWE

```
---
title: "My book"
site: bookdown::bookdown_site
output:
  bookdown::pdf_book: default
  bookdown::gitbook:
    split_by: "section+number"
---

# Cross-referrences {-}

| Target | Label |
| ------ | ----- |
| Part I | \@ref(p:A) |
| Chapter 1 | \@ref(ch:1) |
| Section 1.1 | \@ref(s:1:1) |
| Section 1.2 | \@ref(s:1:2) |
| Chapter 2 | \@ref(ch:2) |
| Section 2.1 | \@ref(s:2:1) |
| Section 2.2 | \@ref(s:2:2) |

# Chapter 1 {#ch:1}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis sapien porttitor, sollicitudin turpis id, aliquam nulla. Nulla velit metus, vestibulum at lacus viverra, scelerisque accumsan ligula. Quisque vehicula massa eget gravida scelerisque. Integer id dictum nulla. Cras hendrerit aliquam velit at blandit. Nunc a velit magna. Mauris euismod fringilla lorem. Aenean venenatis ut mi quis euismod. Cras dictum venenatis diam id ultricies.

## Section 1.1 {#s:1:1}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis sapien porttitor, sollicitudin turpis id, aliquam nulla. Nulla velit metus, vestibulum at lacus viverra, scelerisque accumsan ligula. Quisque vehicula massa eget gravida scelerisque. Integer id dictum nulla. Cras hendrerit aliquam velit at blandit. Nunc a velit magna. Mauris euismod fringilla lorem. Aenean venenatis ut mi quis euismod. Cras dictum venenatis diam id ultricies.

## Section 1.2 {#s:1:2}

Nulla consequat orci et augue semper bibendum. Phasellus et tortor blandit, dapibus sem a, volutpat nibh. Quisque euismod justo sed mi congue fringilla. Ut eu orci eget sem viverra feugiat eget et orci. Suspendisse nisi orci, condimentum quis massa in, mollis suscipit odio. Sed facilisis elit a urna euismod elementum. Mauris vel risus sed arcu consectetur venenatis. Mauris aliquam, dui in sodales ornare, lectus diam congue felis, eget fringilla turpis justo vel sem. Donec tristique quis massa ac fermentum. Ut sed pulvinar tellus. Fusce est turpis, sagittis eu nibh et, dictum posuere lacus. Nullam pretium neque ac libero auctor fringilla. Maecenas tempor nisl at turpis lacinia, a elementum purus volutpat. 

# (PART) Part I {- #p:A}

# Chapter 2 {#ch:2}

## Section 2.1 {#s:2:1}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis sapien porttitor, sollicitudin turpis id, aliquam nulla. Nulla velit metus, vestibulum at lacus viverra, scelerisque accumsan ligula. Quisque vehicula massa eget gravida scelerisque. Integer id dictum nulla. Cras hendrerit aliquam velit at blandit. Nunc a velit magna. Mauris euismod fringilla lorem. Aenean venenatis ut mi quis euismod. Cras dictum venenatis diam id ultricies.

## Section 2.2 {#s:2:2}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis sapien porttitor, sollicitudin turpis id, aliquam nulla. Nulla velit metus, vestibulum at lacus viverra, scelerisque accumsan ligula. Quisque vehicula massa eget gravida scelerisque. Integer id dictum nulla. Cras hendrerit aliquam velit at blandit. Nunc a velit magna. Mauris euismod fringilla lorem. Aenean venenatis ut mi quis euismod. Cras dictum venenatis diam id ultricies.
```
## `xfun::session_info('bookdown')`

```
R version 3.6.1 (2019-07-05) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Ubuntu 18.04.3 LTS, RStudio 1.2.5001  
Locale:   LC_CTYPE=nl_NL.UTF-8       LC_NUMERIC=C               LC_TIME=nl_BE.UTF-8        LC_COLLATE=nl_NL.UTF-8     LC_MONETARY=nl_BE.UTF-8    LC_MESSAGES=nl_NL.UTF-8      LC_PAPER=nl_BE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_BE.UTF-8 LC_IDENTIFICATION=C         
Package version:   base64enc_0.1.3 bookdown_0.14.1 digest_0.6.21   evaluate_0.14   glue_1.3.1      graphics_3.6.1  grDevices_3.6.1 highr_0.8       htmltools_0.4.0 jsonlite_1.6      knitr_1.25      magrittr_1.5    markdown_1.1    methods_3.6.1   mime_0.7        Rcpp_1.0.2      rlang_0.4.0     rmarkdown_1.16  stats_3.6.1     stringi_1.4.3     stringr_1.4.0   tinytex_0.16    tools_3.6.1     utils_3.6.1     xfun_0.10       yaml_2.2.0
```
---

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by becarioprecario** [comment]
I have a similar problem when compiling my book. Chapter and section numbers are replaced by ?? but the HTML links are correct. My feeling is that it must be related to panic. Does this help?

https://github.com/jgm/pandoc/issues/5941

There, the Pandoc developers claim that it is a bookdown error as 'The syntax you're using to generate a chapter reference is not part of pandoc itself; an external tool must be resolving this.'

**Comment by becarioprecario** [comment]
Also, I have run pandoc from the console (adding --filter /usr/local/bin/pandoc-crossref, which was not in the command run by book down) and I get this warning:

WARNING: pandoc-crossref was compiled with pandoc 2.8 but is being run through 2.8.1. This is not supported. Strange things may (and likely will) happen silently.

I am running this on a Mac OS X Mojave with the latest versions of pandoc* from home-brew.

**Comment by cderv** [comment]
I think there is two issues now. 

One as described initially here with pandoc 2.7 (and earlier maybe). The labels are not correctly found and it differs depending on  `split_by`

Now there is another one with Pandoc 2.8+ because more labels are not found now. It could be related to some changes following https://github.com/rstudio/bookdown/issues/832
I can reproduce with 2.9.1 and have some more error. I must look into the previous fix because there may be something missing 🤔 

The labels detection needs to be fixed for both here, that is for sure.

**Comment by becarioprecario** [comment]
As a workaround, I am simply using pandoc and pandoc-citeproc provided by RStudio. I have just added them early in my PATH and this seems to work fine and may be a temporary solution.

**Comment by cderv** [comment]
Here the first part of my investigation. I began to deal with the bug using pandoc 2.7

First there one things unsupported in the example of @ThierryO :

PART title can't really be reference at, and can't have ids. You have no page with Part 1, it is only in the toc on the left. So `# (PART) Part I {- #p:A}` will not work. Bookdown does support only `# (PART) Part I {-}` like shown in [the book](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers). This means you can't reference it using `\@ref`
This is  why you get the `??` and the warning as not found.

For the chapter 2 issue, there is indeed a bug in bookdown for a very specific case: When using `split_by: session` and when a second header follows directly a first header with no text in between. 

To reproduce be sure to have pandoc 2.7 (or earlier I guess) and here is a minimal document
````
---
title: "My book"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: 
    split_by: "section"
---

# Cross-referrences {-}

| Target | Label |
| ------ | ----- |
| Chapter 1 | \@ref(ch:1) |
| Section 1.1 | \@ref(s:1:1) |

# Chapter 1 {#ch:1}

## Section 1.1 {#s:1:1}
````
You'll get a 
```r
Warning message:
The label(s) ch:1 not found
```

This is because bookdown processing will add a closing `div` tag, to support special bookdown feature, when `split_by`  is `section` or `section+number`
https://github.com/rstudio/bookdown/blob/70f9c07b2049f772b377956047421172069193d9/R/html.R#L282

When the second header follows directly the first header, it will add this closing ` \n</div>` to the end of the h1 header. This will break `parse_section_labels()` that won't find the id because the regex does not take into account this addition. 
https://github.com/rstudio/bookdown/blob/70f9c07b2049f772b377956047421172069193d9/R/html.R#L700-L707

A fix will be to modify the regex adding a `( \n</div>)?` before `$`. 
With this fix, no more warnings and reference is ok. 

It is possible a similar fix in `reg_chap` is required for figure label parsing. Will require some tests.

I will later on investigate the behavior with pandoc 2.9+ to see if the cross referencing still works and what change pandoc introduced and that should be reported in bookdown. 

Hope it helps.

**Comment by ThierryO** [comment]
I disagree that `# (PART) Part I {- #p:A}` is invalid syntax. It yields sensible output when generating a pdf (`\@ref` works). While I agree that a PART doesn't get it own page, it still gets a number in the toc. The hyperlink could point to the first page within the PART.

**Comment by cderv** [comment]
> I disagree that # (PART) Part I {- #p:A} is invalid syntax. It yields sensible output when generating a pdf (\@ref works). 

From the source code and the doc, I was under the impression that adding ids to (PART) header was not (yet) supported. Since you do not understand the same, I will check again then in details how it is currently supposed to work as I am not yet sure if it is a bug or a feature request.  

Please understand that I do my best to help the community when I have available time as I know a bit the internal of rmarkdown ecosystem. So, I really appreciate you thoughts and reactions, Thanks!

**Comment by cderv** [comment]
> The hyperlink could point to the first page within the PART.

@ThierryO I think this is a feature request asked recently in https://github.com/rstudio/bookdown/issues/847. You may discuss it there.

**Comment by cderv** [comment]
I suggested a PR to fix the cross referencing issue that happens using `split_by: sections` or `split_by: sections+number`. 
It does not add a feature to reference the `(PART)` header. This is now discussed in another issue. (https://github.com/rstudio/bookdown/issues/787#issuecomment-573302814)

@becarioprecario I think the issue with cross reference and pandoc 2.9+ has been fixed in last bookdown version (see [NEWS](https://github.com/rstudio/bookdown/blob/master/NEWS.md#bug-fixes))

**Comment by yihui** [comment]
Many thanks to @cderv for the fix! You may test the development version via

```r
remotes::install_github('rstudio/bookdown')
```
