### ISSUE TITLE
Some social sharing links do not work

### ISSUE THREAD

**Issue by MateuszKalamarz** [rstudio/bookdown#797]
It seems to me that some social sharing links that appear in the top right of the top bar do not work. I've checked it in properly hosted site. The URL of the website is **https://perso.in/testy/**

The links I checked:
1. Facebook - opens new window with error message. The link that I am redirected to is: https://www.facebook.com/sharer/sharer.php?s=100&p[url]=https%3A%2F%2Fperso.in%2Ftesty%2F
![image](https://user-images.githubusercontent.com/57257538/68090893-a25ccf00-fe79-11e9-8e16-a76acb1a55c3.png)
2. Twitter - opens main page but there is nothing inside tweet textbox. The link that I am redirected to is: https://twitter.com/home?status=Og%C3%B3lnopolskie%20Badanie%20Trener%C3%B3w%20-%20Raport%20https%3A%2F%2Fperso.in%2Ftesty%2F
3. LinkedIn - works just fine. I am redirected to the page where I can select wether I want to share it in private message or as a post. The link that I am redirected to is: https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fperso.in%2Ftesty%2F

Pandoc version 2.7.2. `xfun::session_info('bookdown')` output:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.2.5001

Locale:
  LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
  LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

Package version:
  base64enc_0.1.3 bookdown_0.14.1 digest_0.6.22   evaluate_0.14   glue_1.3.1      graphics_3.6.1 
  grDevices_3.6.1 highr_0.8       htmltools_0.4.0 jsonlite_1.6    knitr_1.25      magrittr_1.5   
  markdown_1.1    methods_3.6.1   mime_0.7        Rcpp_1.0.2      rlang_0.4.1     rmarkdown_1.16 
  stats_3.6.1     stringi_1.4.3   stringr_1.4.0   tinytex_0.17    tools_3.6.1     utils_3.6.1    
  xfun_0.10       yaml_2.2.0   
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for the report. 

I believe these are not so often use feature because it seems that there were changes from some time now in how to share with those tools.  Here is a [generator](http://sharelinkgenerator.com/) for different website and an updated documentation in great [css-trick website](https://css-tricks.com/simple-social-sharing-links/)

* Facebook: The parameters in url seems to have changed. It should now be
https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fperso.in%2Ftesty%2F

* Twitter: The way to share seems also to have changed. See [dev guide](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview). It should be now:
https://twitter.com/intent/tweet?text=Og%C3%B3lnopolskie%20Badanie%20Trener%C3%B3w%20-%20Raport%20https%3A%2F%2Fperso.in%2Ftesty%2F

* linkedin: it should be 
https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fperso.in%2Ftesty%2F

I'll do a PR as soon as I can to get all this up to date and working again.
