### ISSUE TITLE
[FR] Option to insert Disqus

### ISSUE THREAD

**Issue by gaow** [rstudio/bookdown#81]
I'm interested to see an option that can insert a Disqus section to HTML pages. A particular user case that motivates the request is to create via bookdown a lab notebook to organize daily research, where analysis procedures are published allowing for random comments be made by colleagues on the same page under the Disqus section.

Thank you!

**Comment by yihui** [comment]
Thanks for the suggestion! Personally I do not like Disqus (primarily because they don't support Markdown), but there isn't another choice. I feel it may be better to let readers write comments using Github issues.

**Comment by samuel-rosa** [comment]
@yihui, I agree with you that it is more productive to have readers writing comments using GitHub issues. But what if the user has no knowledge of GitHub or has very low computer skills? In those situations, which include a lot of my potential readers, using Disqus would be far more efficient (reader-wise) than using GitHub issues. Perhaps @gaow will agree with me on that.

**Comment by znmeb** [comment]
I don't like Disqus, but then comments are a time sink for an author anyhow. Also, I'd like to stay independent of third parties (Disqus comments, GitHub issues) wherever possible.

**Comment by samuel-rosa** [comment]
@znmeb, do you have any suggestion?

**Comment by znmeb** [comment]
@samuel-rosa I'm looking at the Coral Project (<https://github.com/coralproject/reef>).

**Comment by yihui** [comment]
You can consider this service hypothes.is and it works with any URLs, e.g. https://via.hypothes.is/https://bookdown.org/yihui/bookdown/ Readers can highlight text and make comments, and you can choose to turn off all comments or just read the normal URL https://bookdown.org/yihui/bookdown/.

**Comment by benmarwick** [comment]
[Discourse](https://github.com/discourse/discourse) can be an embedded comment service, and supports markdown

**Comment by znmeb** [comment]
I went with GitHub issues, since my book is hosted on GitHub anyway. I tried to get a Twitter button embed to work but only got a link and gave up. There's also WebMentions, which I've implemented. https://github.com/converspace/webmention/blob/master/README.md

**Comment by samuel-rosa** [comment]
I think hypothes.is can be embedded in your webpage using `<script async defer src="https://hypothes.is/embed.js"></script>`.

**Comment by yihui** [comment]
@samuel-rosa Yes, I was aware of that. I didn't want to embed the script on the pages because the buttons at the top-right covers share buttons on the gitbook toolbar. I want to readers to make comments either through https://via.hypothes.is/https://bookdown.org/yihui/bookdown/ or by installing the Chrome extension, or use the hypothes.is bookmark.

**Comment by yihui** [comment]
FYI https://bookdown.org/yihui/bookdown/collaboration.html

**Comment by pssguy** [comment]
@yihui Thanks for providing disqus option. Is there any way of excluding it from specific chapters?

**Comment by yihui** [comment]
@pssguy As a Disqus forum admin, you can close comments on certain pages, e.g. I closed comments at http://yihui.name/knitr/ It is not possible to exclude the comments section on certain pages. It will be written to all pages.

**Comment by joelgombin** [comment]
@benmarwick mentions that Discourse can be used as a comment backend (more about this [here](https://meta.discourse.org/t/discourse-plugin-for-static-site-generators-like-jekyll-or-octopress/7965/116) for example). How would you go about integrationg Discourse to a bookdown project?

**Comment by yihui** [comment]
@joelgombin I don't think I need to do anything to integrate a particular comment system, as long as the system is based on HTML/JavaScript. It does not matter if it is Disqus or other systems. The idea is the same: use the `includes` option.

**Comment by joelgombin** [comment]
Thanks @yihui, it is indeed much simpler than I expected. For those who moght be interested in using Discourse as their back end for comments, the easiest reference is actually https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963/11. 
There might be a slight difficulty, though: the embedded javascript code requires the url of the webpage (so the url of the page you're generating with bookdown). The domain can be indicated manually, since it is only known by the author, of course ; but what about the relative path of any given webpage? Is there any automatic way of generating it (i.e., something similar to a `{{page.url}}` liquid tag)?
