### ISSUE TITLE
Support iterative embedded content

### ISSUE THREAD

**Issue by BenPortner** [rstudio/bookdown#824]
Hi there,

First off, I love bookdown. Keep up the good work!

### setup
I write a gitbook `doc.Rmd`. I want to include an HTML figure `fig.html`. The figure itself contains an image `img.png`. 

### problem
`fig.html` is correctly embedded. However, `img.png` cannot be shown because it is not automatically copied to the output folder. Only `doc.html` and `fig.html` are in the folder.

### code

doc.Rmd:
```
![some caption](fig.html)
```

fig.html:
```{html}
<html>
  <head>
  </head>
  <body>
    <img src="img.png"></img>
  </body>
</html>
```

### proposed solution
Bookdown would need to look into the html file, detect  `src` attributes and copy the specified files over with the other content.

### session info

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Locale:
  LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
  LC_TIME=German_Germany.1252    

Package version:
  base64enc_0.1.3 bookdown_0.15   digest_0.6.21   evaluate_0.14   glue_1.3.1      graphics_3.6.1  grDevices_3.6.1 highr_0.8      
  htmltools_0.4.0 jsonlite_1.6    knitr_1.26      magrittr_1.5    markdown_1.1    methods_3.6.1   mime_0.7        Rcpp_1.0.2     
  rlang_0.4.0     rmarkdown_1.16  stats_3.6.1     stringi_1.4.3   stringr_1.4.0   tinytex_0.17    tools_3.6.1     utils_3.6.1    
  xfun_0.11       yaml_2.2.0 

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
  - I could not read the guide because the URL is blocked by the enterprise firewall.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi @BenPortner, 

Thank you for your patience. 

I am not sure to quite understand the use case here. It feels odd to me to include an image using a full HTML file like this. However, I'll try to give some hints on what to do. 

The syntax used is to include an image using Markdown syntax. See https://pandoc.org/MANUAL.html#images 
```
![some caption](file/path)
```
This is Pandoc which process this syntax not **bookdown**

For a HTML file, `![some caption](figs.html)` will lead to a `<embed>` tag in HTML because the figure you provide is an HTML file (not a PNG file to use with `<img>` for example).

By default, when using `self_contained = TRUE` format output option, Pandoc will make all content self contained inside the HTML file by encoding everything. (meaning the fig.html file won't even be needed by the main HTML).
However, this may not work correctly in that case - it depends on the format and insertion (it is a Pandoc thing). 

You can use a non self contained format, or with recent Pandoc, you can force to not encode the result (and link to the fig.html file directly)

````markdown
---
title: demo
output: 
  bookdown::html_document2: default
---

![some caption](fig.html){data-external=1}
````

Pandoc will generate this HTML then
````html
<div class="figure">
<embed src="fig.html" data-external="1"></embed>
<p class="caption">some caption</p>
</div>
```

And you'll have the HTML file embeded in your result
![image](https://user-images.githubusercontent.com/6791940/112822987-f842a000-9088-11eb-841b-b27f5e7764fc.png)


If you want an image, an image format (png, svg, ...) needs to be used.

I'll close this as this is not related to **bookdown** specifically.
