### ISSUE TITLE
New version of bookdown is very slow

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#842]
Just upgraded to latest bookdown (0.16) and it feels substantially slower in the final step than the previous verison.

**Comment by yihui** [comment]
I just tested bookdown 0.15 and 0.16 with

```sh
time Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', quiet = TRUE)"
```

on the **bookdown** book, and I don't see a big difference in the time (both versions take about 8 seconds).

I doubt if it was due to updating **bookdown**. It might be due to **knitr**: https://github.com/yihui/knitr/issues/1781 (I haven't got time to deal with it yet, but it is a one-time issue---if you compile the book again, the cache will work properly).

**Comment by cderv** [comment]
This is quite old now. (version is now 0.21).
If speed of **bookdown** rendering is still a concerned, we can reopen a new issue and look into it.
