### ISSUE TITLE
`geometry` metadata option has only an effect in `index.Rmd`

### ISSUE THREAD

**Issue by pat-s** [rstudio/bookdown#850]
One can change the output geometry for PDF via the [pandoc metadata field `geometry`](https://stackoverflow.com/a/13516042/4185785).

While other options such as `fontsize` or `documentclass` can be specified in `output.yml`, the `geometry` option is only picked up when set in `index.Rmd`.

Not sure if this is a bug or intended but I haven't found it document anywhere.

Example of a custom geometry in `index.Rmd`:

```yml
geometry:
  - top=1in
  - left=0.7in
  - right=0.7in
  - bottom=1in
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
We can say this is a bug, but I doubt if it will ever be fixed. The cause for this bug is that we detect if there is a `geometry` field in the Rmd, and if there isn't, we use `margin:1in` as its default value: https://github.com/rstudio/rmarkdown/blob/10253799eaab80e3cbb86973cd20d0a3fc38655b/R/pdf_document.R#L164

In **rmarkdown**, we only read YAML metadata from the first YAML block, which can be considered as a bug (any YAML blocks should be considered). If you specify `geometry` in another YAML block in another Rmd file, **rmarkdown** won't be able to detect it, hence will use the default `margin:1in`.

I wonder what's the use case of specifying the `geometry` settings in other Rmd files but not `index.Rmd`.
