### ISSUE TITLE
Redundant removal of attributes on HTML headers

### ISSUE THREAD

**Issue by salim-b** [rstudio/bookdown#865]
I just noticed that when using Bookdown/Blogdown in combination with Pandoc 2.9+, the following JavaScript dependency gets inserted in the rendered HTML:

```html
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
```

The content of `header-attrs.js` is found [here](https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/h/pandoc/header-attrs.js) and was added with https://github.com/rstudio/rmarkdown/commit/7f51e232c98b2f7db40b40cd593385fe76b3189b.

At the same time, the R function `bookdown:::clean_header_tags()` removes those attributes during rendering (added with https://github.com/rstudio/bookdown/commit/a07ae075a92b7031a514f6f31f5f89bd6c84b498).

So – if I didn't miss anything – this header attribute removal is done twice: At first during rendering the R Markdown to HTML using R code (fine) and a second time during rendering the HTML by the browser using JS code (redundant and thus obsolete in the case of Bookdown/Blogdown).

Therefore I think it would make sense to avoid adding this JS dependency when bookdown/blogdown renders a file. Or maybe, the R-based header attribute removal could be performed directly by `rmarkdown::render()` (instead of adding the JS).

(IMHO: The less JS, the better 😬)

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
Thanks for the analysis! There is indeed redundancy. For **bookdown**, we have to keep a07ae07, so the only option is to get rid of `header-attrs.js`, which is currently not possible. I agree with you that the less JS the better, but this JS script is only 12 lines, and I'm not sure if it is worth the effort to provide an option to exclude it...

**Comment by salim-b** [comment]
> so the only option is to get rid of `header-attrs.js`, which is currently not possible.

?

> Or maybe, the R-based header attribute removal could be performed directly by `rmarkdown::render()`?

This isn't an option?

**Comment by yihui** [comment]
> the R-based header attribute removal could be performed directly by `rmarkdown::render()`?

I don't know how to do this...

`rmarkdown::html_document()` introduced `header-attrs.js` (as an HTML dependency), and if I understand you correctly, you want to remove it for **bookdown** output formats, but I don't know how to remove it.

**Comment by cderv** [comment]
Overall, I think we should make JS script in **rmarkdown** more conditional than they are. So that a user can decide to opt-out a feature brought by a JS script if desired. Doing so in **rmarkdown** would allow to opt-out in **bookdown**.

Otherwise, maybe we should start setting a knitr option in each package format so that **rmarkdown** can sometimes adapt its behavior depending on which the format is ? 

Like we do for **bookdown** label but more generic, something like 
```r
knitr:::opts_knit$set(bookdown = TRUE)
```

This would be set in a bookdown format, so that it can be used by other packages that needs to modify their behavior.

@yihui what do you think ?

**Comment by yihui** [comment]
Perhaps adding `getOption('rmarkdown.html_dependency.header_attr', TRUE)` before `pandoc_available('2.9')`: https://github.com/rstudio/rmarkdown/blob/6e572ca665d19d05aadb08a4309fc5478b840aee/R/html_dependencies.R#L424

so that we can set this option to `FALSE` in **bookdown**.

**Comment by salim-b** [comment]
Another thing I've noticed: The header attribute removal executed by `header-attrs.js` breaks anchor link highlighting in pkgdown articles (vignettes).

Since `rmarkdown:::html_dependency_header_attrs()` is added *unconditionally* in `rmarkdown::html_document_base()`, the user cannot easily change that...

Why do header attributes need to be removed in the first place again?

**Comment by cderv** [comment]
> Why do header attributes need to be removed in the first place again?

This is a long old story due to a Pandoc change but it started here: rstudio/rmarkdown#1723

As commented in the file (https://github.com/rstudio/rmarkdown/blob/e44a23f3e508534966717e9c9dce07afd2e37002/R/html_dependencies.R#L440)
> Pandoc 2.9 adds attributes on both headers and their parent divs. We remove
the ones on headers since they are unnecessary

At first it was a quick fix for tabsets in rmarkdown following a change in Pandoc 2.8, and then became more generic for other format (like flexdashboard (https://github.com/rstudio/rmarkdown/pull/1732) . At last, it was changed to the current code applied only for Pandoc 2.9 and later (https://github.com/rstudio/rmarkdown/commit/7f51e232c98b2f7db40b40cd593385fe76b3189b) so that it works the same for different pandoc version (except 2.8 which will be buggy anyway). 

We still need to provide an opt out way as discussed in https://github.com/rstudio/bookdown/issues/865#issuecomment-827052647

This will be done for next version of **rmarkdown**
