### ISSUE TITLE
Theorem environments no longer work in LaTeX/PDF output with Pandoc >= 2.7.3

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#883]
Because Pandoc converts `<div class='foo'></div>` to `\begin{foo}\end{foo}` now.

I'm a little surprised that no one has reported it so far. Perhaps this feature is rarely used by anyone... Anyway, this is a nasty bug and needs to be fixed soon.

https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

**Comment by yihui** [comment]
For anyone reading this issue and has the same problem, please:

```r
remotes::install_github('yihui/knitr')
```

**Comment by tchevri** [comment]
Sorry to trouble you - I tried your fix and it did not work for me (just to confirm and make sure I did not screw up anything, my `knitr` version is 1.28.9 after running your command) . As per your earlier request, [I posted as a comment back on SO](https://stackoverflow.com/questions/61922964/bookdown-to-pdf-theorem-environment-duplicate).

**Comment by cderv** [comment]
Thanks for the report @tchevri. I can reproduce. As it bugged me, I spend all my spare time from the last two days trying to understand what is wrong with the fix. 
 
After some times, I started again from the beginning no considering the current fix and I think I found the issue.

> Because Pandoc converts <div class='foo'></div> to \begin{foo}\end{foo} now.

@yihui I did a few checks, and I think this comes from our recent `latex-div.lua` filter. That would mean it happens with every pandoc version. 

See this reprex: the environment is created from a Div, only if I activate our filter. 
``` r
test_in <- tempfile()
test_out <- tempfile(fileext = ".tex")
xfun::write_utf8(
  '<div class="definition">something</div>',
  test_in
)
# using last pandoc
rmarkdown::pandoc_version()
#> [1] '2.9.2.1'
# by default, pandoc does not create an environment from a Div
rmarkdown::pandoc_convert(test_in, to = 'latex', from = "html", 
                          output = test_out, verbose = TRUE)
#> "C:/Users/chris/scoop/shims/pandoc" +RTS -K512m -RTS "C:\Users\chris\AppData\Local\Temp\RtmpG6BPN2\file5e8052eb5c38" --to latex --from html --output "C:\Users\chris\AppData\Local\Temp\RtmpG6BPN2\file5e8089c27a9.tex"
xfun::read_utf8(test_out)
#> [1] "something"
# with our filter, an environment is created from a div
rmarkdown::pandoc_convert(test_in, to = 'latex', from = "html", 
                          output = test_out, verbose = TRUE,
                          options = rmarkdown:::pandoc_lua_filters("latex-div.lua"))
#> "C:/Users/chris/scoop/shims/pandoc" +RTS -K512m -RTS "C:\Users\chris\AppData\Local\Temp\RtmpG6BPN2\file5e8052eb5c38" --to latex --from html --output "C:\Users\chris\AppData\Local\Temp\RtmpG6BPN2\file5e8089c27a9.tex" --lua-filter "C:/Users/chris/Documents/R/win-library/3.6/rmarkdown/rmd/lua/latex-div.lua"
xfun::read_utf8(test_out)
#> [1] "\\begin{definition}" ""                    "something"          
#> [4] ""                    "\\end{definition}"
unlink(c(test_in, test_out))
```

<sup>Created on 2020-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I think the fix should be either
* in our filter so that we do **really** nothing if no `data-latex` attribute is provided
* or we should apply your fix for all pandoc version and consider that rmarkdown will convert Div to latex environment. (What pandoc does not want to do I think (reading at https://github.com/jgm/pandoc/issues/5880#issuecomment-550079609)

What do you think ?

**Comment by yihui** [comment]
@cderv I'm still hesitating on if the `data-latex` attribute should be mandatory. Now I feel it probably should, since I have been surprised a few times that `<div>` is also converted to LaTeX environments (I was only expecting `::: {}` to be converted). Anyway, https://github.com/yihui/knitr/commit/3f085054f9d686c0e5102bd38075e0686c2689b1 should fix @tchevri's problem. Please try:

```r
remotes::install_github('yihui/knitr')
```

Thanks!

**Comment by cderv** [comment]
I am still searching if there is a way to apply lua filer only on fenced div, and not explicit `<div>`. 
It seems we may need to make the `data-latex` mandatory, or make the filter latex-div optional so that people can choose to opt-in, with the known consequences. Currently it applies to each rendering with any tools that uses rmarkdown and convert to PDF.

**Comment by yihui** [comment]
I just reverted https://github.com/rstudio/rmarkdown/commit/14127ac0223e2a56d4ff9d3b5dd78925143caf03 with https://github.com/rstudio/rmarkdown/commit/b2cff70c523b1bd6a7269fc8c28ee9ca9f51c71a. I'll update the R Markdown Cookbook soon.

> I am still searching if there is a way to apply lua filer only on fenced div, and not explicit `<div>`.

I feel this may not be possible. Pandoc's parser treats them as identical:

```
 % echo '<div class="foo">abc</div>' | pandoc -f markdown -t native
[Div ("",["foo"],[])
 [Plain [Str "abc"]]]

% echo '::: foo\nabc\n:::' | pandoc -f markdown -t native
[Div ("",["foo"],[])
 [Para [Str "abc"]]]
```

**Comment by cderv** [comment]
Shouldn't we also revert the change in knitr that closed this issue ? 
```html
<div class="environment">
```
won't be converted to latex environment anymore.

**Comment by RLesur** [comment]
> I feel this may not be possible. Pandoc's parser treats them as identical:

Pandoc can treat them differently if one disables the [`native_divs` extension](https://pandoc.org/MANUAL.html#native_divs) (this extension is enabled by default for markdown input).

**Comment by yihui** [comment]
@cderv It doesn't matter. I mean https://github.com/yihui/knitr/commit/6907b428572c130982f6b3d6c91a164a15b94a30 doesn't hurt.

@RLesur Thanks for the tip!
