### ISSUE TITLE
Could I replace the colons after "Figure 1.1" with whitespace?

### ISSUE THREAD

**Issue by AzureRabbit** [rstudio/bookdown#901]
@yihui 
I want to remove the ":" in fig.caption ("Figure 1.1: ").

I guess it would be work if i add `fig.cap.sep = " "`, but it doesn't work.
```
```{r echo = FALSE, message=FALSE, fig.align='center', fig.cap='aabb', fig.cap.sep = " ", out.width="50%"}

knitr::include_graphics("images/figaabb.jpg")
```` 

how to make it work?
Thanks!

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

which output are you working with ? 

If you are trying to produce PDF, you can use classic tex customization. 
Adding this in you latex header will change the separator for you pdf output
```latex
\usepackage{caption}
\captionsetup[figure]{labelsep=space}
```
Look at `caption` Tex 📦  documentation or [this](http://www.peteryu.ca/tutorials/publishing/latex_captions) to get some hint on what could be done. 

This works for pdf because this is Latex which is responsible for generating the caption numbering. 

For other format, this is bookdown, and currently there is no way to customize the separator. 
https://github.com/rstudio/bookdown/blob/3bb46f4d29c64789d94fdb4cf5692c46c86c73c4/R/html.R#L656

This is a feature request that seems feasible to add as an option for bookdown. I think this would make sense to make it book wide and not on a per-chunk basis. 🤔 but it would work only for non pdf output.  For PDF format, this would still require to be customized by latex preamble though...

unless we find a way to make it the same for all output. Not trivial

hope it helps for now

**Comment by AzureRabbit** [comment]
> Hi,
> 
> which output are you working with ?
> 
> If you are trying to produce PDF, you can use classic tex customization.
> Adding this in you latex header will change the separator for you pdf output
> 
> ```
> \usepackage{caption}
> \captionsetup[figure]{labelsep=space}
> ```
> 
> Look at `caption` Tex 📦 documentation or [this](http://www.peteryu.ca/tutorials/publishing/latex_captions) to get some hint on what could be done.
> 
> This works for pdf because this is Latex which is responsible for generating the caption numbering.
> 
> For other format, this is bookdown, and currently there is no way to customize the separator.
> https://github.com/rstudio/bookdown/blob/3bb46f4d29c64789d94fdb4cf5692c46c86c73c4/R/html.R#L656
> 
> This is a feature request that seems feasible to add as an option for bookdown. I think this would make sense to make it book wide and not on a per-chunk basis. 🤔 but it would work only for non pdf output. For PDF format, this would still require to be customized by latex preamble though...
> 
> unless we find a way to make it the same for all output. Not trivial
> 
> hope it helps for now

@cderv Thank you very much, I understand.  The pdf solution is good enough for me,  for other format,  it doesn't matter.
