### ISSUE TITLE
Consider 3-column format

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#922]
For many sites, a 3 column format where you have cross-page links, content, and in-page links provides an effective navigation system, e.g. https://jestjs.io/docs/en/snapshot-testing#inline-snapshots. It would be great to have this option built-in to bookdown.

**Comment by apreshill** [comment]
I would also love this feature. See also:

+ https://jupyterbook.org/intro.html
+ https://arm.rbind.io/prework/
+ https://gohugo.io/templates/introduction/

**Comment by jtbayly** [comment]
It took me forever to figure out what the third column in the jupyterbook example was. The naming is important. The others get it right with "on this page." 

Not sure I really like the idea, though. We've got the "on this page" content included in the TOC right now. Why doesn't that work?

**Comment by apreshill** [comment]
@jtbayly can you say more about what you mean by:

> We've got the "on this page" content included in the TOC right now. Why doesn't that work?

I don't have an explorable per chapter TOC with links unless I configure the book's TOC to show that level.

**Comment by jtbayly** [comment]
That's all I mean. The left-hand sidebar contains the navigation of the whole TOC (to whatever level you want people to be able to see it), and allows collapsing of the levels not in focus. Isn't that precisely what you want?

**Comment by apreshill** [comment]
Thanks for clarifying.

> Isn't that precisely what you want?
No.

**Comment by jtbayly** [comment]
I'm all for greater flexibility and choice in terms of templates! I'm just not seeing how it is helpful to separate the table of contents of the chapter out of its larger context. It confused me for a long time on the Jupiter page. I want to know where I am in the book. The way the TOC works right now is that I can see at a glance, "I'm in this chapter, this section of the chapter." One is a subset of the other. When you separate them out, it makes me ask which one I'm "in." That's why I said the wording is important. 

I'm not trying to argue that your use-case for three columns is wrong, though. I know I often want to do something that other people think is silly. :-) Plus, more designs for output would just strengthen the ecosystem, I think.

**Comment by apreshill** [comment]
I think it just depends on your use case. When I made the [stat545](https://stat545.com/) bookdown book, I thought that for some of the chapters, the expansion on the left-side was so large (with so many sub-sections) that it clouded my vision of the global book TOC, especially on smaller screens. On the other hand, with the [blogdown](https://bookdown.org/yihui/blogdown/) book, we left the TOC all fully expanded. This means things feel less jumpy, but you never see the TOC in full- you have to scroll. I have heard feedback that the 3-column layout isn't as intuitive, but having seen it across a number of documentation sites only over the past 6 months, I've come around to it as an effective option for some use cases.

**Comment by cderv** [comment]
New `bs4_book()` format has the 3 column layout.
